// Generated by RcppR6 (0.2.4): do not edit by hand
#ifndef _LEAF_RCPPR6_PRE_HPP_
#define _LEAF_RCPPR6_PRE_HPP_

#include <RcppCommon.h>


namespace leaf {
namespace RcppR6 {
template <typename T> class RcppR6;
}
}



namespace Rcpp {
template <typename T> SEXP wrap(const leaf::RcppR6::RcppR6<T>&);
namespace traits {
template <typename T> class Exporter<leaf::RcppR6::RcppR6<T> >;
}

template <> SEXP wrap(const leaf::Leaf&);
template <> leaf::Leaf as(SEXP);
}

#endif
