// Generated by RcppR6 (0.2.4): do not edit by hand
#ifndef _LEAF_RCPPR6_POST_HPP_
#define _LEAF_RCPPR6_POST_HPP_

#include <Rcpp.h>
#include <leaf/RcppR6_support.hpp>

namespace leaf {
namespace RcppR6 {
namespace traits {
template <> inline std::string   class_name_r<leaf::Leaf >() {return "Leaf";}
template <> inline std::string   package_name<leaf::Leaf >() {return "leaf";}
template <> inline std::string generator_name<leaf::Leaf >() {return ".R6_Leaf";}
}
}
}

namespace Rcpp {
template <typename T>
SEXP wrap(const leaf::RcppR6::RcppR6<T>& x) {
  return x.to_R6();
}

namespace traits {
template <typename T>
class Exporter<leaf::RcppR6::RcppR6<T> > {
public:
  Exporter(SEXP x) : obj(leaf::RcppR6::RcppR6<T>(x)) {}
  inline leaf::RcppR6::RcppR6<T> get() { return obj; }
private:
  leaf::RcppR6::RcppR6<T> obj;
};
}

template <> inline SEXP wrap(const leaf::Leaf& x) {
  return wrap(leaf::RcppR6::RcppR6<leaf::Leaf>(x));
}
template <> inline leaf::Leaf as(SEXP x) {
  return *(leaf::RcppR6::RcppR6<leaf::Leaf>(x));
}
}

#endif
