// Generated by RcppR6 (0.2.4): do not edit by hand
#ifndef _PHYLLOPTIM_RCPPR6_POST_HPP_
#define _PHYLLOPTIM_RCPPR6_POST_HPP_

#include <Rcpp.h>
#include <phylloptim/RcppR6_support.hpp>

namespace phylloptim {
namespace RcppR6 {
namespace traits {
template <> inline std::string   class_name_r<phylloptim::Leaf >() {return "Leaf";}
template <> inline std::string   package_name<phylloptim::Leaf >() {return "phylloptim";}
template <> inline std::string generator_name<phylloptim::Leaf >() {return ".R6_Leaf";}
}
}
}

namespace Rcpp {
template <typename T>
SEXP wrap(const phylloptim::RcppR6::RcppR6<T>& x) {
  return x.to_R6();
}

namespace traits {
template <typename T>
class Exporter<phylloptim::RcppR6::RcppR6<T> > {
public:
  Exporter(SEXP x) : obj(phylloptim::RcppR6::RcppR6<T>(x)) {}
  inline phylloptim::RcppR6::RcppR6<T> get() { return obj; }
private:
  phylloptim::RcppR6::RcppR6<T> obj;
};
}

template <> inline SEXP wrap(const phylloptim::Leaf& x) {
  return wrap(phylloptim::RcppR6::RcppR6<phylloptim::Leaf>(x));
}
template <> inline phylloptim::Leaf as(SEXP x) {
  return *(phylloptim::RcppR6::RcppR6<phylloptim::Leaf>(x));
}
}

#endif
