// Generated by RcppR6 (0.2.4): do not edit by hand
#ifndef _PHYLLOPTIM_RCPPR6_POST_HPP_
#define _PHYLLOPTIM_RCPPR6_POST_HPP_

#include <Rcpp.h>
#include <phylloptim/RcppR6_support.hpp>

namespace phylloptim {
namespace RcppR6 {
namespace traits {
template <> inline std::string   class_name_r<phylloptim::RootNetwork >() {return "RootNetwork";}
template <> inline std::string   package_name<phylloptim::RootNetwork >() {return "phylloptim";}
template <> inline std::string generator_name<phylloptim::RootNetwork >() {return "";}
template <> inline std::string   class_name_r<phylloptim::Leaf >() {return "Leaf";}
template <> inline std::string   package_name<phylloptim::Leaf >() {return "phylloptim";}
template <> inline std::string generator_name<phylloptim::Leaf >() {return ".R6_Leaf";}
}
}
}

namespace Rcpp {
template <typename T>
SEXP wrap(const phylloptim::RcppR6::RcppR6<T>& x) {
  return x.to_R6();
}

namespace traits {
template <typename T>
class Exporter<phylloptim::RcppR6::RcppR6<T> > {
public:
  Exporter(SEXP x) : obj(phylloptim::RcppR6::RcppR6<T>(x)) {}
  inline phylloptim::RcppR6::RcppR6<T> get() { return obj; }
private:
  phylloptim::RcppR6::RcppR6<T> obj;
};
}

template <> inline SEXP wrap(const phylloptim::RootNetwork& x) {
  Rcpp::List ret;
  ret["r_R_H_min"] = Rcpp::wrap(x.r_R_H_min);
  ret["r_R_V_sum"] = Rcpp::wrap(x.r_R_V_sum);
  ret["c_r_V"] = Rcpp::wrap(x.c_r_V);
  ret["c_r_H"] = Rcpp::wrap(x.c_r_H);
  ret["r_R_V"] = Rcpp::wrap(x.r_R_V);
  ret.attr("class") = "RootNetwork";
  return ret;
}
template <> inline phylloptim::RootNetwork as(SEXP x) {
  if (!phylloptim::RcppR6::is<phylloptim::RootNetwork >(x)) {
    Rcpp::stop("Expected an object of type RootNetwork");
    // NOTE: Won't drop through or return anything.
  }
  // NOTE: assumes default constructable, and will assign *every*
  // field twice.  No current support for a hook.
  phylloptim::RootNetwork ret;
  Rcpp::List xl(x);
  // ret.r_R_H_min = Rcpp::as<decltype(retr_R_H_min) >(xl["r_R_H_min"]);
  ret.r_R_H_min = Rcpp::as<std::vector<double> >(xl["r_R_H_min"]);
  // ret.r_R_V_sum = Rcpp::as<decltype(retr_R_V_sum) >(xl["r_R_V_sum"]);
  ret.r_R_V_sum = Rcpp::as<std::vector<double> >(xl["r_R_V_sum"]);
  // ret.c_r_V = Rcpp::as<decltype(retc_r_V) >(xl["c_r_V"]);
  ret.c_r_V = Rcpp::as<std::vector<double> >(xl["c_r_V"]);
  // ret.c_r_H = Rcpp::as<decltype(retc_r_H) >(xl["c_r_H"]);
  ret.c_r_H = Rcpp::as<std::vector<double> >(xl["c_r_H"]);
  // ret.r_R_V = Rcpp::as<decltype(retr_R_V) >(xl["r_R_V"]);
  ret.r_R_V = Rcpp::as<std::vector<double> >(xl["r_R_V"]);
  return ret;
}
template <> inline SEXP wrap(const phylloptim::Leaf& x) {
  return wrap(phylloptim::RcppR6::RcppR6<phylloptim::Leaf>(x));
}
template <> inline phylloptim::Leaf as(SEXP x) {
  return *(phylloptim::RcppR6::RcppR6<phylloptim::Leaf>(x));
}
}

#endif
