// Generated by RcppR6 (0.2.4): do not edit by hand
#ifndef _PHYLLOPTIM_RCPPR6_PRE_HPP_
#define _PHYLLOPTIM_RCPPR6_PRE_HPP_

#include <RcppCommon.h>


namespace phylloptim {
namespace RcppR6 {
template <typename T> class RcppR6;
}
}



namespace Rcpp {
template <typename T> SEXP wrap(const phylloptim::RcppR6::RcppR6<T>&);
namespace traits {
template <typename T> class Exporter<phylloptim::RcppR6::RcppR6<T> >;
}

template <> SEXP wrap(const phylloptim::RootNetwork&);
template <> phylloptim::RootNetwork as(SEXP);
template <> SEXP wrap(const phylloptim::Leaf&);
template <> phylloptim::Leaf as(SEXP);
}

#endif
