// The batched trait gradient, exposed to R (issue #4, PLAN 11d stage 2).
//
// NOT generated by RcppR6, and not in inst/RcppR6_classes.yml, for the same
// reason src/root_network.cpp is not: these are free functions, and RcppR6 only
// generates class glue. A plain Rcpp attribute is the whole mechanism.
//
// THREE FUNCTIONS, AND THE SPLIT BETWEEN THEM IS THE POINT.
//
//   * `gradient_par_names()` hands the parameter enumeration back to R so the two
//     orders can be compared in a test rather than trusted.
//   * `gradient_batch_prepare()` converts N observations' drivers to C++ ONCE and
//     returns a pointer to them. ⚠️ This is not premature: a `RootNetwork` costs
//     60-100 us to cross the boundary -- 60x a trivial `.Call` -- because it is an
//     RcppR6 `list:` class and every crossing rebuilds a five-element named list.
//     Converting per call would cost 80 ms for a 1,327-row batch and swamp the
//     ~13 ms of gradient it was carrying.
//   * `gradient_batch_run()` is the hot path: ONE crossing per likelihood
//     evaluation, carrying a parameter matrix in and three arrays out.
//
// The `Leaf` is the caller's, passed per call. That costs one pointer unwrap and
// means construction -- ~204 us from R, some 70 solves -- is paid once for the
// whole fit rather than once per gradient (#52).
#include <phylloptim.h>

#include <string>
#include <vector>

namespace {

// The prepared drivers. A vector rather than a class: there is no state to keep
// consistent, and `Rcpp::XPtr` deletes it when R garbage-collects the handle.
using DriverBatch = std::vector<phylloptim::gradient::Drivers>;

std::vector<double> numeric_at(const Rcpp::List& x, R_xlen_t i) {
  return Rcpp::as<std::vector<double> >(x[i]);
}

// ⚠️ A pointer restored from `saveRDS()` or carried into a new session is a NULL
// externalptr, and dereferencing one segfaults the session rather than erroring.
// So it is checked, once, at every entry point that takes a handle.
DriverBatch* checked(SEXP drivers) {
  if (TYPEOF(drivers) != EXTPTRSXP) {
    Rcpp::stop("this is not a prepared batch; build one with leaf_batch()");
  }
  Rcpp::XPtr<DriverBatch> p(drivers);
  if (p.get() == NULL) {
    Rcpp::stop("this leaf_batch()'s drivers are gone -- it holds a C++ pointer, "
               "so it does not survive saveRDS() or a new session. Rebuild it "
               "with leaf_batch().");
  }
  return p.get();
}

}  // namespace

//' The differentiable parameters, in the order C++ indexes them
//'
//' The fourteen [leaf_traits()] in `set_traits()`'s argument order, then
//' `leaf_specific_conductance_max` and `resistance`. Exported so that R's own
//' copy of this order can be compared against it in a test: R passes integer
//' positions into this enumeration, so appending to it is safe and reordering it
//' would silently differentiate the wrong parameter.
//'
//' @return A character vector, one entry per differentiable parameter.
//' @seealso [leaf_gradient_batch()]
//' @examples
//' gradient_par_names()
//' @export
// [[Rcpp::export]]
std::vector<std::string> gradient_par_names() {
  return phylloptim::gradient::par_names();
}

//' The cost curves, in the order C++ indexes them
//'
//' Every optimality model this package implements, as names, in the order of the
//' `CostCurve` enumeration. R selects a curve by its POSITION in this vector, so
//' the vector is read back out of C++ rather than restated in R: appending a curve
//' is safe and reordering the enumeration would silently solve a different model.
//'
//' @return A character vector of curve names.
//' @seealso [cost_curve_has_derivative()], [leaf_gradient()]
//' @examples
//' cost_curve_names()
//' @export
// [[Rcpp::export]]
std::vector<std::string> cost_curve_names() {
  std::vector<std::string> out;
  for (int i = 0; ; ++i) {
    const std::string nm = phylloptim::Leaf::curve_name(i);
    if (nm == "unknown") break;
    out.push_back(nm);
  }
  return out;
}

//' Which cost curves have an analytic first derivative
//'
//' `TRUE` where `dprofit/dpsi_stem` exists, which is what a gradient needs in
//' order to test stationarity and to apply the implicit function theorem.
//'
//' It is `FALSE` for the **product** objectives. Those maximise `A * g(psi)`
//' rather than `A - C(psi)`, so their derivative is `(dA/dpsi)*g + A*g'` and not
//' the `dA/dpsi - dC/dpsi` the shared expression computes. They remain solvable
//' through their own optimisers; only the exact gradient is unavailable.
//'
//' @return A logical vector parallel to [cost_curve_names()].
//' @seealso [cost_curve_names()]
//' @examples
//' stats::setNames(cost_curve_has_derivative(), cost_curve_names())
//' @export
// [[Rcpp::export]]
std::vector<bool> cost_curve_has_derivative() {
  std::vector<bool> out;
  for (int i = 0; ; ++i) {
    if (phylloptim::Leaf::curve_name(i) == "unknown") break;
    out.push_back(phylloptim::Leaf::curve_has_derivative(i));
  }
  return out;
}

//' The differentiated outputs, in the order C++ indexes them
//'
//' `A`, `gc`, `psi_stem`, `collar` and `profit`. Unlike [gradient_par_names()],
//' which R holds its own copy of and a test compares, R **reads** this one — so
//' the list exists once and adding an output is one edit rather than two that
//' can disagree.
//'
//' The first four are what a gas-exchange calibration observes; `profit` is what
//' a demographic consumer bills, and it is the one output the envelope theorem
//' reaches. See [leaf_gradient()].
//'
//' @return A character vector of five names.
//' @seealso [leaf_gradient()], [leaf_gradient_batch()]
//' @examples
//' gradient_output_names()
//' @export
// [[Rcpp::export]]
std::vector<std::string> gradient_output_names() {
  return phylloptim::gradient::output_names();
}

// Convert N observations' drivers to C++ once. Everything is already resolved
// and recycled to length N on the R side by `leaf_batch()`, which calls
// `.resolve_drivers()` per row -- so the defaults (1 m layers, the nominal
// networks, the single path's placeholder depth) have exactly one definition and
// it is not this one.
// [[Rcpp::export]]
SEXP gradient_batch_prepare(Rcpp::List root_network, Rcpp::List psi_soil,
                            Rcpp::List soil_depth, Rcpp::NumericVector PPFD,
                            Rcpp::NumericVector atm_vpd,
                            Rcpp::NumericVector ca,
                            Rcpp::NumericVector leaf_temp,
                            Rcpp::NumericVector atm_o2_kpa,
                            Rcpp::NumericVector atm_kpa) {
  const R_xlen_t n = root_network.size();
  if (psi_soil.size() != n || soil_depth.size() != n || PPFD.size() != n ||
      atm_vpd.size() != n || ca.size() != n || leaf_temp.size() != n ||
      atm_o2_kpa.size() != n || atm_kpa.size() != n) {
    Rcpp::stop("gradient_batch_prepare(): every driver must have one entry per "
               "observation");
  }
  DriverBatch* out = new DriverBatch();
  out->reserve(static_cast<std::size_t>(n));
  for (R_xlen_t i = 0; i < n; ++i) {
    phylloptim::gradient::Drivers d;
    d.root_network = Rcpp::as<phylloptim::RootNetwork>(root_network[i]);
    d.psi_soil = numeric_at(psi_soil, i);
    d.soil_depth = numeric_at(soil_depth, i);
    d.PPFD = PPFD[i];
    d.atm_vpd = atm_vpd[i];
    d.ca = ca[i];
    d.leaf_temp = leaf_temp[i];
    d.atm_o2_kpa = atm_o2_kpa[i];
    d.atm_kpa = atm_kpa[i];
    out->push_back(d);
  }
  return Rcpp::XPtr<DriverBatch>(out, true);
}

// Called by `leaf_gradient_batch()` before it touches either handle, so that a
// dead batch is reported by `checked()` above rather than by whichever pointer
// Rcpp happens to unwrap first -- which says "external pointer is not valid", a
// true statement that gives no hint the fix is to rebuild.
// [[Rcpp::export]]
void gradient_batch_check(SEXP drivers) { checked(drivers); }

// The hot path. `theta` is n x 15 (or 1 x 15, shared), `pars` is ZERO-BASED
// positions into `gradient_par_names()`, and the supply path is read off the
// leaf rather than passed, so the caller cannot name one path while handing over
// a leaf built on the other.
// [[Rcpp::export]]
Rcpp::List gradient_batch_run(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_,
                              SEXP drivers, Rcpp::NumericMatrix theta,
                              Rcpp::IntegerVector pars, double step,
                              double stationarity_tol, std::string method,
                              bool fast_stem_curve, SEXP psi,
                              SEXP dpsi_dtheta, int curve, double fd_step,
                              double pinned_A_max) {
  DriverBatch* batch_drivers = checked(drivers);
  const std::size_t n = batch_drivers->size();
  const std::size_t npars = static_cast<std::size_t>(pars.size());

  if (theta.ncol() != phylloptim::gradient::n_pars) {
    Rcpp::stop("gradient_batch_run(): `theta` must have %d columns",
               phylloptim::gradient::n_pars);
  }
  const std::size_t theta_nrow = static_cast<std::size_t>(theta.nrow());
  if (theta_nrow != 1 && theta_nrow != n) {
    Rcpp::stop("gradient_batch_run(): `theta` must have 1 row or one per "
               "observation");
  }
  for (R_xlen_t k = 0; k < pars.size(); ++k) {
    if (pars[k] < 0 || pars[k] >= phylloptim::gradient::n_pars) {
      Rcpp::stop("gradient_batch_run(): `pars` is out of range");
    }
  }

  phylloptim::gradient::Settings settings;
  settings.step = step;
  settings.stationarity_tol = stationarity_tol;
  settings.fast_stem_curve = fast_stem_curve;
  settings.curve = curve;
  settings.fd_step = fd_step;
  settings.pinned_A_max = pinned_A_max;
  if (method == "auto") {
    settings.method = phylloptim::gradient::Method::Auto;
  } else if (method == "ift") {
    settings.method = phylloptim::gradient::Method::Ift;
  } else if (method == "fd") {
    settings.method = phylloptim::gradient::Method::Fd;
  } else {
    Rcpp::stop("gradient_batch_run(): `method` must be auto, ift or fd");
  }

  // `pars` is copied into an int vector rather than read out of the
  // Rcpp::IntegerVector inside the loop so that nothing on the hot path touches
  // R's memory: the model can throw, and unwinding through Rcpp proxies is the
  // one thing that has to stay simple here.
  const std::vector<int> par_idx(pars.begin(), pars.end());

  // `psi` is NULL to solve, or one collar potential per observation to impose;
  // `dpsi_dtheta` is then an n x npars matrix. R validates both -- shape,
  // positivity and the `method` conflict -- so this only holds the shape it was
  // promised, and says so rather than reading past the end if it was not.
  Rcpp::NumericVector psi_v;
  Rcpp::NumericVector dpsi_v;
  const double* psi_p = nullptr;
  const double* dpsi_p = nullptr;
  if (psi != R_NilValue) {
    psi_v = Rcpp::as<Rcpp::NumericVector>(psi);
    if (static_cast<std::size_t>(psi_v.size()) != n) {
      Rcpp::stop("gradient_batch_run(): `psi` must have one value per "
                 "observation");
    }
    psi_p = psi_v.begin();
    if (dpsi_dtheta != R_NilValue) {
      dpsi_v = Rcpp::as<Rcpp::NumericVector>(dpsi_dtheta);
      if (static_cast<std::size_t>(dpsi_v.size()) != n * npars) {
        Rcpp::stop("gradient_batch_run(): `dpsi_dtheta` must be n x npars");
      }
      dpsi_p = dpsi_v.begin();
    }
  }

  const std::vector<phylloptim::gradient::Result> res =
      phylloptim::gradient::batch(*obj_, theta.begin(), theta_nrow,
                                  *batch_drivers,
                                  obj_->supply_kind_name() == "single",
                                  par_idx.data(), npars, settings, psi_p,
                                  dpsi_p);

  const int n_out = phylloptim::gradient::n_outputs;
  Rcpp::NumericMatrix value(static_cast<int>(n), n_out);
  Rcpp::NumericVector grad(static_cast<R_xlen_t>(n) *
                           static_cast<R_xlen_t>(npars) * n_out);
  Rcpp::CharacterVector status(static_cast<R_xlen_t>(n));
  Rcpp::CharacterVector method_used(static_cast<R_xlen_t>(n));
  Rcpp::CharacterVector message(static_cast<R_xlen_t>(n));
  Rcpp::NumericVector H(static_cast<R_xlen_t>(n));
  Rcpp::NumericVector stationarity(static_cast<R_xlen_t>(n));
  Rcpp::NumericMatrix M(static_cast<int>(n), static_cast<int>(npars));
  Rcpp::NumericMatrix dY_dpsi(static_cast<int>(n), n_out);
  Rcpp::NumericVector psi_used(static_cast<R_xlen_t>(n));

  for (std::size_t i = 0; i < n; ++i) {
    const phylloptim::gradient::Result& r = res[i];
    for (int j = 0; j < n_out; ++j) {
      value(static_cast<int>(i), j) = r.value[j];
      dY_dpsi(static_cast<int>(i), j) = r.dY_dpsi[j];
    }
    for (std::size_t k = 0; k < npars; ++k) {
      M(static_cast<int>(i), static_cast<int>(k)) =
          k < r.M.size() ? r.M[k] : NA_REAL;
    }
    psi_used[i] = r.psi;
    // R's array layout: [i, k, j] lives at i + n*k + n*npars*j.
    for (std::size_t k = 0; k < npars; ++k) {
      for (int j = 0; j < n_out; ++j) {
        grad[i + n * k + n * npars * static_cast<std::size_t>(j)] =
            r.grad[k * static_cast<std::size_t>(n_out) +
                   static_cast<std::size_t>(j)];
      }
    }
    status[i] = phylloptim::gradient::status_name(r.status);
    // `method` names the route, and a prescribed collar is a third one: neither
    // "ift" (nothing was derived from -M/H) nor "fd" (the solve was not
    // differenced).
    //
    // ⚠️ `psi_p` is CALL-level, so this does not vary across `i` -- the whole
    // batch is prescribed or none of it is. A row that threw therefore reports
    // `status = "error"` with `method = "prescribed"`, which is right: `method`
    // says which route was asked for, and `status` says what happened to the row.
    method_used[i] = psi_p != nullptr
                         ? "prescribed"
                         : (r.used_ift ? "ift" : "fd");
    message[i] = r.message;
    H[i] = r.H;
    stationarity[i] = r.stationarity;
  }

  grad.attr("dim") = Rcpp::IntegerVector::create(
      static_cast<int>(n), static_cast<int>(npars), n_out);

  return Rcpp::List::create(
      Rcpp::_["value"] = value, Rcpp::_["gradient"] = grad,
      Rcpp::_["status"] = status, Rcpp::_["method"] = method_used,
      Rcpp::_["H"] = H, Rcpp::_["stationarity"] = stationarity,
      Rcpp::_["M"] = M, Rcpp::_["dY_dpsi"] = dY_dpsi,
      Rcpp::_["psi"] = psi_used, Rcpp::_["message"] = message);
}
