// Generated by RcppR6 (0.2.4): do not edit by hand
#include <leaf.h>

// [[Rcpp::export]]
leaf::Leaf Leaf__ctor(double vcmax_25, double stem_c, double stem_b, double psi_crit, double root_c, double root_b, double root_psi_crit, double beta2, double jmax_25, double a, double curv_fact_elec_trans, double curv_fact_colim, double GSS_tol_abs, double vulnerability_curve_ncontrol, double ci_abs_tol, double ci_niter, double cost_scale_TF24, double beta_R_H, double beta_R_V) {
  return leaf::Leaf(vcmax_25, stem_c, stem_b, psi_crit, root_c, root_b, root_psi_crit, beta2, jmax_25, a, curv_fact_elec_trans, curv_fact_colim, GSS_tol_abs, vulnerability_curve_ncontrol, ci_abs_tol, ci_niter, cost_scale_TF24, beta_R_H, beta_R_V);
}
// [[Rcpp::export]]
void Leaf__initialize_integrator(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, int integration_rule, double integration_tol) {
  obj_->initialize_integrator(integration_rule, integration_tol);
}
// [[Rcpp::export]]
void Leaf__set_physiology(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, const std::vector<double>& root_carbon_per_leaf_area, double PPFD, const std::vector<double>& psi_soil, const std::vector<double>& soil_depth, double leaf_specific_conductance_max, double atm_vpd, double ca, double leaf_temp, double atm_o2_kpa, double atm_kpa) {
  obj_->set_physiology(root_carbon_per_leaf_area, PPFD, psi_soil, soil_depth, leaf_specific_conductance_max, atm_vpd, ca, leaf_temp, atm_o2_kpa, atm_kpa);
}
// [[Rcpp::export]]
double Leaf__proportion_of_conductivity(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double psi) {
  return obj_->proportion_of_conductivity(psi);
}
// [[Rcpp::export]]
double Leaf__arrh_curve(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double Ea, double ref_value, double leaf_temp) {
  return obj_->arrh_curve(Ea, ref_value, leaf_temp);
}
// [[Rcpp::export]]
double Leaf__peak_arrh_curve(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double Ea, double ref_value, double leaf_temp, double H_d, double d_S) {
  return obj_->peak_arrh_curve(Ea, ref_value, leaf_temp, H_d, d_S);
}
// [[Rcpp::export]]
double Leaf__transpiration(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double psi_stem, double psi_upstream) {
  return obj_->transpiration(psi_stem, psi_upstream);
}
// [[Rcpp::export]]
double Leaf__transpiration_full_integration(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double psi_stem, double psi_upstream) {
  return obj_->transpiration_full_integration(psi_stem, psi_upstream);
}
// [[Rcpp::export]]
double Leaf__stom_cond_CO2(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double psi_stem, double psi_upstream) {
  return obj_->stom_cond_CO2(psi_stem, psi_upstream);
}
// [[Rcpp::export]]
double Leaf__transpiration_to_psi_stem(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double transpiration_, double psi_upstream) {
  return obj_->transpiration_to_psi_stem(transpiration_, psi_upstream);
}
// [[Rcpp::export]]
double Leaf__assim_rubisco_limited(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double ci_) {
  return obj_->assim_rubisco_limited(ci_);
}
// [[Rcpp::export]]
double Leaf__assim_electron_limited(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double ci_) {
  return obj_->assim_electron_limited(ci_);
}
// [[Rcpp::export]]
double Leaf__assim_colimited(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double ci_) {
  return obj_->assim_colimited(ci_);
}
// [[Rcpp::export]]
double Leaf__assim_minus_stom_cond_CO2(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double x, double psi_stem, double psi_upstream) {
  return obj_->assim_minus_stom_cond_CO2(x, psi_stem, psi_upstream);
}
// [[Rcpp::export]]
double Leaf__electron_transport(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->electron_transport();
}
// [[Rcpp::export]]
void Leaf__set_leaf_states_rates_from_psi_stem(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double psi_stem, double psi_upstream) {
  obj_->set_leaf_states_rates_from_psi_stem(psi_stem, psi_upstream);
}
// [[Rcpp::export]]
void Leaf__E_from_Soil_to_Root_Collar(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double P_x_r, std::vector<double> psi_soil) {
  obj_->E_from_Soil_to_Root_Collar(P_x_r, psi_soil);
}
// [[Rcpp::export]]
void Leaf__find_root_collar_psi(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  obj_->find_root_collar_psi();
}
// [[Rcpp::export]]
double Leaf__find_root_psi(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double wettest_soil_layer, std::vector<double> psi_soil, int find_root_crit) {
  return obj_->find_root_psi(wettest_soil_layer, psi_soil, find_root_crit);
}
// [[Rcpp::export]]
double Leaf__find_psi_stem_from_psi_root(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double psi_root, std::vector<double> psi_soil) {
  return obj_->find_psi_stem_from_psi_root(psi_root, psi_soil);
}
// [[Rcpp::export]]
double Leaf__evaluate_root_collar_psi(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double target_opt_root_psi) {
  return obj_->evaluate_root_collar_psi(target_opt_root_psi);
}
// [[Rcpp::export]]
double Leaf__dprofit_droot_collar_psi(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double opt_root_psi) {
  return obj_->dprofit_droot_collar_psi(opt_root_psi);
}
// [[Rcpp::export]]
double Leaf__psi_stem_to_ci(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double psi_stem, double psi_upstream) {
  return obj_->psi_stem_to_ci(psi_stem, psi_upstream);
}
// [[Rcpp::export]]
double Leaf__hydraulic_cost_Sperry(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double psi_stem, double psi_upstream) {
  return obj_->hydraulic_cost_Sperry(psi_stem, psi_upstream);
}
// [[Rcpp::export]]
double Leaf__hydraulic_cost_TF(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double psi_stem) {
  return obj_->hydraulic_cost_TF(psi_stem);
}
// [[Rcpp::export]]
double Leaf__profit_psi_stem_Sperry(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double psi_stem, double psi_upstream) {
  return obj_->profit_psi_stem_Sperry(psi_stem, psi_upstream);
}
// [[Rcpp::export]]
double Leaf__profit_psi_stem_TF(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double psi_stem, double psi_upstream) {
  return obj_->profit_psi_stem_TF(psi_stem, psi_upstream);
}
// [[Rcpp::export]]
double Leaf__lambda_TF24(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double psi_stem) {
  return obj_->lambda_TF24(psi_stem);
}
// [[Rcpp::export]]
void Leaf__optimise_psi_stem_Sperry(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  obj_->optimise_psi_stem_Sperry();
}
// [[Rcpp::export]]
void Leaf__optimise_psi_stem_TF(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  obj_->optimise_psi_stem_TF();
}
// [[Rcpp::export]]
double Leaf__medlyn_model_gs(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double assim_colimited_) {
  return obj_->medlyn_model_gs(assim_colimited_);
}
// [[Rcpp::export]]
void Leaf__solve_medlyn_ci_numerical(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  obj_->solve_medlyn_ci_numerical();
}
// [[Rcpp::export]]
void Leaf__solve_medlyn_ci_analytical(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  obj_->solve_medlyn_ci_analytical();
}
// [[Rcpp::export]]
void Leaf__setup_transpiration(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double resolution) {
  obj_->setup_transpiration(resolution);
}
// [[Rcpp::export]]
void Leaf__setup_root_vulnerability(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double resolution) {
  obj_->setup_root_vulnerability(resolution);
}
// [[Rcpp::export]]
double Leaf__ci___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->ci_;
}
// [[Rcpp::export]]
void Leaf__ci___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->ci_ = value;
}

// [[Rcpp::export]]
double Leaf__stom_cond_CO2___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->stom_cond_CO2_;
}
// [[Rcpp::export]]
void Leaf__stom_cond_CO2___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->stom_cond_CO2_ = value;
}

// [[Rcpp::export]]
double Leaf__assim_colimited___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->assim_colimited_;
}
// [[Rcpp::export]]
void Leaf__assim_colimited___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->assim_colimited_ = value;
}

// [[Rcpp::export]]
double Leaf__transpiration___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->transpiration_;
}
// [[Rcpp::export]]
void Leaf__transpiration___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->transpiration_ = value;
}

// [[Rcpp::export]]
std::vector<double> Leaf__soil_consumption___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->soil_consumption_;
}
// [[Rcpp::export]]
void Leaf__soil_consumption___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, std::vector<double> value) {
  obj_->soil_consumption_ = value;
}

// [[Rcpp::export]]
double Leaf__profit___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->profit_;
}
// [[Rcpp::export]]
void Leaf__profit___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->profit_ = value;
}

// [[Rcpp::export]]
double Leaf__psi_stem__get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->psi_stem;
}
// [[Rcpp::export]]
void Leaf__psi_stem__set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->psi_stem = value;
}

// [[Rcpp::export]]
double Leaf__lambda___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->lambda_;
}
// [[Rcpp::export]]
void Leaf__lambda___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->lambda_ = value;
}

// [[Rcpp::export]]
double Leaf__lambda_analytical___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->lambda_analytical_;
}
// [[Rcpp::export]]
void Leaf__lambda_analytical___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->lambda_analytical_ = value;
}

// [[Rcpp::export]]
double Leaf__hydraulic_cost___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->hydraulic_cost_;
}
// [[Rcpp::export]]
void Leaf__hydraulic_cost___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->hydraulic_cost_ = value;
}

// [[Rcpp::export]]
double Leaf__opt_psi_stem___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->opt_psi_stem_;
}
// [[Rcpp::export]]
void Leaf__opt_psi_stem___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->opt_psi_stem_ = value;
}

// [[Rcpp::export]]
double Leaf__opt_root_psi___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->opt_root_psi_;
}
// [[Rcpp::export]]
void Leaf__opt_root_psi___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->opt_root_psi_ = value;
}

// [[Rcpp::export]]
double Leaf__opt_ci___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->opt_ci_;
}
// [[Rcpp::export]]
void Leaf__opt_ci___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->opt_ci_ = value;
}

// [[Rcpp::export]]
double Leaf__E_up___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->E_up_;
}
// [[Rcpp::export]]
void Leaf__E_up___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->E_up_ = value;
}

// [[Rcpp::export]]
double Leaf__assim_max___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->assim_max_;
}
// [[Rcpp::export]]
void Leaf__assim_max___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->assim_max_ = value;
}

// [[Rcpp::export]]
double Leaf__count__get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->count;
}
// [[Rcpp::export]]
void Leaf__count__set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->count = value;
}

// [[Rcpp::export]]
double Leaf__electron_transport___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->electron_transport_;
}
// [[Rcpp::export]]
void Leaf__electron_transport___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->electron_transport_ = value;
}

// [[Rcpp::export]]
double Leaf__gamma___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->gamma_;
}
// [[Rcpp::export]]
void Leaf__gamma___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->gamma_ = value;
}

// [[Rcpp::export]]
double Leaf__ko___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->ko_;
}
// [[Rcpp::export]]
void Leaf__ko___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->ko_ = value;
}

// [[Rcpp::export]]
double Leaf__kc___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->kc_;
}
// [[Rcpp::export]]
void Leaf__kc___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->kc_ = value;
}

// [[Rcpp::export]]
double Leaf__km___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->km_;
}
// [[Rcpp::export]]
void Leaf__km___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->km_ = value;
}

// [[Rcpp::export]]
double Leaf__R_d___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->R_d_;
}
// [[Rcpp::export]]
void Leaf__R_d___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->R_d_ = value;
}

// [[Rcpp::export]]
double Leaf__vcmax___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->vcmax_;
}
// [[Rcpp::export]]
void Leaf__vcmax___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->vcmax_ = value;
}

// [[Rcpp::export]]
double Leaf__jmax___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->jmax_;
}
// [[Rcpp::export]]
void Leaf__jmax___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->jmax_ = value;
}

// [[Rcpp::export]]
double Leaf__PPFD___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->PPFD_;
}
// [[Rcpp::export]]
void Leaf__PPFD___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->PPFD_ = value;
}

// [[Rcpp::export]]
double Leaf__atm_vpd___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->atm_vpd_;
}
// [[Rcpp::export]]
void Leaf__atm_vpd___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->atm_vpd_ = value;
}

// [[Rcpp::export]]
double Leaf__ca___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->ca_;
}
// [[Rcpp::export]]
void Leaf__ca___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->ca_ = value;
}

// [[Rcpp::export]]
double Leaf__leaf_temp___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->leaf_temp_;
}
// [[Rcpp::export]]
void Leaf__leaf_temp___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->leaf_temp_ = value;
}

// [[Rcpp::export]]
double Leaf__atm_o2_kpa___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->atm_o2_kpa_;
}
// [[Rcpp::export]]
void Leaf__atm_o2_kpa___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->atm_o2_kpa_ = value;
}

// [[Rcpp::export]]
double Leaf__atm_kpa___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->atm_kpa_;
}
// [[Rcpp::export]]
void Leaf__atm_kpa___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->atm_kpa_ = value;
}

// [[Rcpp::export]]
double Leaf__leaf_specific_conductance_max___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->leaf_specific_conductance_max_;
}
// [[Rcpp::export]]
void Leaf__leaf_specific_conductance_max___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->leaf_specific_conductance_max_ = value;
}

// [[Rcpp::export]]
std::vector<double> Leaf__soil_depth___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->roots_.soil_depth_;
}
// [[Rcpp::export]]
void Leaf__soil_depth___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, std::vector<double> value) {
  obj_->roots_.soil_depth_ = value;
}

// [[Rcpp::export]]
std::vector<double> Leaf__z_soil_mid___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->roots_.z_soil_mid_;
}
// [[Rcpp::export]]
void Leaf__z_soil_mid___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, std::vector<double> value) {
  obj_->roots_.z_soil_mid_ = value;
}

// [[Rcpp::export]]
double Leaf__dz___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->roots_.dz_;
}
// [[Rcpp::export]]
void Leaf__dz___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->roots_.dz_ = value;
}

// [[Rcpp::export]]
int Leaf__soil_number_of_depths___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->roots_.soil_number_of_depths_;
}
// [[Rcpp::export]]
void Leaf__soil_number_of_depths___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, int value) {
  obj_->roots_.soil_number_of_depths_ = value;
}

// [[Rcpp::export]]
int Leaf__max_soil_layer__get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->roots_.max_soil_layer;
}
// [[Rcpp::export]]
void Leaf__max_soil_layer__set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, int value) {
  obj_->roots_.max_soil_layer = value;
}

// [[Rcpp::export]]
std::vector<double> Leaf__psi_soil___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->roots_.psi_soil_;
}
// [[Rcpp::export]]
void Leaf__psi_soil___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, std::vector<double> value) {
  obj_->roots_.psi_soil_ = value;
}

// [[Rcpp::export]]
std::vector<double> Leaf__c_r_V___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->roots_.network_.c_r_V;
}
// [[Rcpp::export]]
void Leaf__c_r_V___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, std::vector<double> value) {
  obj_->roots_.network_.c_r_V = value;
}

// [[Rcpp::export]]
std::vector<double> Leaf__c_r_H___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->roots_.network_.c_r_H;
}
// [[Rcpp::export]]
void Leaf__c_r_H___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, std::vector<double> value) {
  obj_->roots_.network_.c_r_H = value;
}

// [[Rcpp::export]]
std::vector<double> Leaf__r_R_H_min__get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->roots_.network_.r_R_H_min;
}
// [[Rcpp::export]]
void Leaf__r_R_H_min__set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, std::vector<double> value) {
  obj_->roots_.network_.r_R_H_min = value;
}

// [[Rcpp::export]]
std::vector<double> Leaf__r_R_V__get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->roots_.network_.r_R_V;
}
// [[Rcpp::export]]
void Leaf__r_R_V__set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, std::vector<double> value) {
  obj_->roots_.network_.r_R_V = value;
}

// [[Rcpp::export]]
std::vector<double> Leaf__r_R_V_sum__get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->roots_.network_.r_R_V_sum;
}
// [[Rcpp::export]]
void Leaf__r_R_V_sum__set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, std::vector<double> value) {
  obj_->roots_.network_.r_R_V_sum = value;
}

// [[Rcpp::export]]
std::vector<double> Leaf__f_r__get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->f_r;
}
// [[Rcpp::export]]
void Leaf__f_r__set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, std::vector<double> value) {
  obj_->f_r = value;
}

// [[Rcpp::export]]
bool Leaf__use_energy_balance___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->use_energy_balance_;
}
// [[Rcpp::export]]
void Leaf__use_energy_balance___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, bool value) {
  obj_->use_energy_balance_ = value;
}

// [[Rcpp::export]]
double Leaf__d___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->d_;
}
// [[Rcpp::export]]
void Leaf__d___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->d_ = value;
}

// [[Rcpp::export]]
double Leaf__wind_speed___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->wind_speed_;
}
// [[Rcpp::export]]
void Leaf__wind_speed___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->wind_speed_ = value;
}

// [[Rcpp::export]]
double Leaf__Tair___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->Tair_;
}
// [[Rcpp::export]]
void Leaf__Tair___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->Tair_ = value;
}

// [[Rcpp::export]]
double Leaf__Rn___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->Rn_;
}
// [[Rcpp::export]]
void Leaf__Rn___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->Rn_ = value;
}

// [[Rcpp::export]]
double Leaf__ra___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->ra_;
}
// [[Rcpp::export]]
void Leaf__ra___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->ra_ = value;
}

// [[Rcpp::export]]
double Leaf__medlyn_model_gs___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->medlyn_model_gs_;
}
// [[Rcpp::export]]
void Leaf__medlyn_model_gs___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->medlyn_model_gs_ = value;
}

// [[Rcpp::export]]
double Leaf__g0__get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->g0;
}
// [[Rcpp::export]]
void Leaf__g0__set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->g0 = value;
}

// [[Rcpp::export]]
double Leaf__g1__get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->g1;
}
// [[Rcpp::export]]
void Leaf__g1__set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->g1 = value;
}

// [[Rcpp::export]]
double Leaf__theta_w___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->theta_w_;
}
// [[Rcpp::export]]
void Leaf__theta_w___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->theta_w_ = value;
}

// [[Rcpp::export]]
double Leaf__theta_fc___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->theta_fc_;
}
// [[Rcpp::export]]
void Leaf__theta_fc___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->theta_fc_ = value;
}

// [[Rcpp::export]]
double Leaf__theta___get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->theta_;
}
// [[Rcpp::export]]
void Leaf__theta___set(leaf::RcppR6::RcppR6<leaf::Leaf> obj_, double value) {
  obj_->theta_ = value;
}

// [[Rcpp::export]]
double Leaf__lambda__get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->marginal_cost_water();
}

// [[Rcpp::export]]
double Leaf__lambda_molar__get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->marginal_cost_water_molar();
}

// [[Rcpp::export]]
double Leaf__lambda_multilayer__get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->marginal_cost_water_multilayer();
}

// [[Rcpp::export]]
double Leaf__g1_eff__get(leaf::RcppR6::RcppR6<leaf::Leaf> obj_) {
  return obj_->g1_eff();
}



