// Generated by RcppR6 (0.2.4): do not edit by hand
#include <phylloptim.h>

// [[Rcpp::export]]
SEXP RootNetwork__ctor() {
  return Rcpp::wrap(phylloptim::RootNetwork());
}


// [[Rcpp::export]]
phylloptim::Leaf Leaf__ctor(double vcmax_25, double stem_c, double stem_b, double psi_crit, double root_c, double root_b, double root_psi_crit, double beta2, double jmax_25, double a, double curv_fact_elec_trans, double curv_fact_colim, double GSS_tol_abs, double vulnerability_curve_ncontrol, double ci_abs_tol, double ci_niter, double cost_scale_TF24) {
  return phylloptim::Leaf(vcmax_25, stem_c, stem_b, psi_crit, root_c, root_b, root_psi_crit, beta2, jmax_25, a, curv_fact_elec_trans, curv_fact_colim, GSS_tol_abs, vulnerability_curve_ncontrol, ci_abs_tol, ci_niter, cost_scale_TF24);
}
// [[Rcpp::export]]
std::vector<double> Leaf__operating_point_values(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->operating_point_values();
}
// [[Rcpp::export]]
void Leaf__initialize_integrator(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, int integration_rule, double integration_tol) {
  obj_->initialize_integrator(integration_rule, integration_tol);
}
// [[Rcpp::export]]
void Leaf__set_physiology(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, const phylloptim::RootNetwork& root_network, double PPFD, const std::vector<double>& psi_soil, const std::vector<double>& soil_depth, double leaf_specific_conductance_max, double atm_vpd, double ca, double leaf_temp, double atm_o2_kpa, double atm_kpa) {
  obj_->set_physiology(root_network, PPFD, psi_soil, soil_depth, leaf_specific_conductance_max, atm_vpd, ca, leaf_temp, atm_o2_kpa, atm_kpa);
}
// [[Rcpp::export]]
void Leaf__perturb_stem_b(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double stem_b) {
  obj_->perturb_stem_b(stem_b);
}
// [[Rcpp::export]]
void Leaf__set_traits(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double vcmax_25, double stem_c, double stem_b, double psi_crit, double root_c, double root_b, double root_psi_crit, double beta2, double jmax_25, double a, double curv_fact_elec_trans, double curv_fact_colim, double cost_scale_TF24, double R_d_25) {
  obj_->set_traits(vcmax_25, stem_c, stem_b, psi_crit, root_c, root_b, root_psi_crit, beta2, jmax_25, a, curv_fact_elec_trans, curv_fact_colim, cost_scale_TF24, R_d_25);
}
// [[Rcpp::export]]
double Leaf__proportion_of_conductivity(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double psi) {
  return obj_->proportion_of_conductivity(psi);
}
// [[Rcpp::export]]
double Leaf__arrh_curve(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double Ea, double ref_value, double leaf_temp) {
  return obj_->arrh_curve(Ea, ref_value, leaf_temp);
}
// [[Rcpp::export]]
double Leaf__peak_arrh_curve(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double Ea, double ref_value, double leaf_temp, double H_d, double d_S) {
  return obj_->peak_arrh_curve(Ea, ref_value, leaf_temp, H_d, d_S);
}
// [[Rcpp::export]]
double Leaf__transpiration(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double psi_stem, double psi_upstream) {
  return obj_->transpiration(psi_stem, psi_upstream);
}
// [[Rcpp::export]]
double Leaf__transpiration_full_integration(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double psi_stem, double psi_upstream) {
  return obj_->transpiration_full_integration(psi_stem, psi_upstream);
}
// [[Rcpp::export]]
double Leaf__stom_cond_CO2(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double psi_stem, double psi_upstream) {
  return obj_->stom_cond_CO2(psi_stem, psi_upstream);
}
// [[Rcpp::export]]
double Leaf__transpiration_to_psi_stem(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double transpiration_, double psi_upstream) {
  return obj_->transpiration_to_psi_stem(transpiration_, psi_upstream);
}
// [[Rcpp::export]]
double Leaf__assim_rubisco_limited(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double ci_) {
  return obj_->assim_rubisco_limited(ci_);
}
// [[Rcpp::export]]
double Leaf__assim_electron_limited(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double ci_) {
  return obj_->assim_electron_limited(ci_);
}
// [[Rcpp::export]]
double Leaf__assim_colimited(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double ci_) {
  return obj_->assim_colimited(ci_);
}
// [[Rcpp::export]]
double Leaf__assim_minus_stom_cond_CO2(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double x, double psi_stem, double psi_upstream) {
  return obj_->assim_minus_stom_cond_CO2(x, psi_stem, psi_upstream);
}
// [[Rcpp::export]]
double Leaf__electron_transport(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->electron_transport();
}
// [[Rcpp::export]]
double Leaf__leaf_temp_from_E(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double E) {
  return obj_->leaf_temp_from_E(E);
}
// [[Rcpp::export]]
void Leaf__set_leaf_states_rates_from_psi_stem(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double psi_stem, double psi_upstream) {
  obj_->set_leaf_states_rates_from_psi_stem(psi_stem, psi_upstream);
}
// [[Rcpp::export]]
void Leaf__E_from_Soil_to_Root_Collar(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double P_x_r, std::vector<double> psi_soil) {
  obj_->E_from_Soil_to_Root_Collar(P_x_r, psi_soil);
}
// [[Rcpp::export]]
void Leaf__find_root_collar_psi(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  obj_->find_root_collar_psi();
}
// [[Rcpp::export]]
double Leaf__find_root_psi(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double wettest_soil_layer, std::vector<double> psi_soil, int find_root_crit) {
  return obj_->find_root_psi(wettest_soil_layer, psi_soil, find_root_crit);
}
// [[Rcpp::export]]
double Leaf__find_psi_stem_from_psi_root(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double psi_root, std::vector<double> psi_soil) {
  return obj_->find_psi_stem_from_psi_root(psi_root, psi_soil);
}
// [[Rcpp::export]]
double Leaf__evaluate_root_collar_psi(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double target_opt_root_psi) {
  return obj_->evaluate_root_collar_psi(target_opt_root_psi);
}
// [[Rcpp::export]]
double Leaf__dprofit_droot_collar_psi(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double opt_root_psi) {
  return obj_->dprofit_droot_collar_psi(opt_root_psi);
}
// [[Rcpp::export]]
std::vector<double> Leaf__dprofit_droot_collar_psi_checked(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double opt_root_psi) {
  return obj_->dprofit_droot_collar_psi_checked(opt_root_psi);
}
// [[Rcpp::export]]
double Leaf__psi_stem_to_ci(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double psi_stem, double psi_upstream) {
  return obj_->psi_stem_to_ci(psi_stem, psi_upstream);
}
// [[Rcpp::export]]
double Leaf__hydraulic_cost_TF(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double psi_stem) {
  return obj_->hydraulic_cost_TF(psi_stem);
}
// [[Rcpp::export]]
double Leaf__hydraulic_cost_CowanFarquhar(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double psi_stem, double psi_upstream) {
  return obj_->hydraulic_cost_CowanFarquhar(psi_stem, psi_upstream);
}
// [[Rcpp::export]]
double Leaf__profit_psi_stem_TF(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double psi_stem, double psi_upstream) {
  return obj_->profit_psi_stem_TF(psi_stem, psi_upstream);
}
// [[Rcpp::export]]
double Leaf__profit_psi_stem_CowanFarquhar(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double psi_stem, double psi_upstream) {
  return obj_->profit_psi_stem_CowanFarquhar(psi_stem, psi_upstream);
}
// [[Rcpp::export]]
double Leaf__lambda_TF24(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double psi_stem) {
  return obj_->lambda_TF24(psi_stem);
}
// [[Rcpp::export]]
void Leaf__optimise_psi_stem_CowanFarquhar(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  obj_->optimise_psi_stem_CowanFarquhar();
}
// [[Rcpp::export]]
double Leaf__thermal_cost_at(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double leaf_temp) {
  return obj_->thermal_cost_at(leaf_temp);
}
// [[Rcpp::export]]
void Leaf__prepare_profitmax(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  obj_->prepare_profitmax();
}
// [[Rcpp::export]]
double Leaf__profit_psi_stem_ProfitMax(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double psi_stem, double psi_upstream) {
  return obj_->profit_psi_stem_ProfitMax(psi_stem, psi_upstream);
}
// [[Rcpp::export]]
std::vector<double> Leaf__profitmax_curve(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, int n) {
  return obj_->profitmax_curve(n);
}
// [[Rcpp::export]]
void Leaf__optimise_psi_stem_ProfitMax(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  obj_->optimise_psi_stem_ProfitMax();
}
// [[Rcpp::export]]
void Leaf__optimise_psi_stem_TF(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  obj_->optimise_psi_stem_TF();
}
// [[Rcpp::export]]
double Leaf__medlyn_model_gs(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double assim_colimited_) {
  return obj_->medlyn_model_gs(assim_colimited_);
}
// [[Rcpp::export]]
void Leaf__solve_medlyn_ci_numerical(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  obj_->solve_medlyn_ci_numerical();
}
// [[Rcpp::export]]
void Leaf__solve_medlyn_ci_analytical(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  obj_->solve_medlyn_ci_analytical();
}
// [[Rcpp::export]]
void Leaf__set_supply_multilayer(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  obj_->set_supply_multilayer();
}
// [[Rcpp::export]]
void Leaf__set_supply_single(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double gravity_head) {
  obj_->set_supply_single(gravity_head);
}
// [[Rcpp::export]]
void Leaf__setup_transpiration(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double resolution) {
  obj_->setup_transpiration(resolution);
}
// [[Rcpp::export]]
void Leaf__setup_root_vulnerability(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double resolution) {
  obj_->setup_root_vulnerability(resolution);
}
// [[Rcpp::export]]
double Leaf__vcmax_25__get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->vcmax_25;
}

// [[Rcpp::export]]
double Leaf__jmax_25__get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->jmax_25;
}

// [[Rcpp::export]]
double Leaf__stem_c__get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->stem_c;
}

// [[Rcpp::export]]
double Leaf__stem_b__get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->stem_b;
}

// [[Rcpp::export]]
double Leaf__psi_crit__get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->psi_crit;
}

// [[Rcpp::export]]
double Leaf__root_c__get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->roots_.root_c;
}

// [[Rcpp::export]]
double Leaf__root_b__get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->roots_.root_b;
}

// [[Rcpp::export]]
double Leaf__root_psi_crit__get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->roots_.root_psi_crit;
}

// [[Rcpp::export]]
double Leaf__beta2__get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->beta2;
}

// [[Rcpp::export]]
double Leaf__a__get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->a;
}

// [[Rcpp::export]]
double Leaf__curv_fact_elec_trans__get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->curv_fact_elec_trans;
}

// [[Rcpp::export]]
double Leaf__curv_fact_colim__get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->curv_fact_colim;
}

// [[Rcpp::export]]
double Leaf__cost_scale_TF24__get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->cost_scale_TF24;
}

// [[Rcpp::export]]
double Leaf__ci___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->ci_;
}
// [[Rcpp::export]]
void Leaf__ci___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->ci_ = value;
}

// [[Rcpp::export]]
double Leaf__stom_cond_CO2___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->stom_cond_CO2_;
}
// [[Rcpp::export]]
void Leaf__stom_cond_CO2___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->stom_cond_CO2_ = value;
}

// [[Rcpp::export]]
double Leaf__assim_colimited___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->assim_colimited_;
}
// [[Rcpp::export]]
void Leaf__assim_colimited___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->assim_colimited_ = value;
}

// [[Rcpp::export]]
double Leaf__transpiration___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->transpiration_;
}
// [[Rcpp::export]]
void Leaf__transpiration___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->transpiration_ = value;
}

// [[Rcpp::export]]
std::vector<double> Leaf__soil_consumption___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->soil_consumption_;
}
// [[Rcpp::export]]
void Leaf__soil_consumption___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, std::vector<double> value) {
  obj_->soil_consumption_ = value;
}

// [[Rcpp::export]]
double Leaf__profit___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->profit_;
}
// [[Rcpp::export]]
void Leaf__profit___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->profit_ = value;
}

// [[Rcpp::export]]
double Leaf__psi_stem__get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->psi_stem;
}
// [[Rcpp::export]]
void Leaf__psi_stem__set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->psi_stem = value;
}

// [[Rcpp::export]]
double Leaf__lambda___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->lambda_;
}
// [[Rcpp::export]]
void Leaf__lambda___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->lambda_ = value;
}

// [[Rcpp::export]]
double Leaf__carbon_gain___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->carbon_gain_;
}
// [[Rcpp::export]]
void Leaf__carbon_gain___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->carbon_gain_ = value;
}

// [[Rcpp::export]]
double Leaf__hydraulic_cost_norm___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->hydraulic_cost_norm_;
}
// [[Rcpp::export]]
void Leaf__hydraulic_cost_norm___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->hydraulic_cost_norm_ = value;
}

// [[Rcpp::export]]
double Leaf__thermal_cost___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->thermal_cost_;
}
// [[Rcpp::export]]
void Leaf__thermal_cost___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->thermal_cost_ = value;
}

// [[Rcpp::export]]
double Leaf__hydraulic_cost___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->hydraulic_cost_;
}
// [[Rcpp::export]]
void Leaf__hydraulic_cost___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->hydraulic_cost_ = value;
}

// [[Rcpp::export]]
double Leaf__opt_psi_stem___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->opt_psi_stem_;
}
// [[Rcpp::export]]
void Leaf__opt_psi_stem___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->opt_psi_stem_ = value;
}

// [[Rcpp::export]]
double Leaf__opt_root_psi___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->opt_root_psi_;
}
// [[Rcpp::export]]
void Leaf__opt_root_psi___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->opt_root_psi_ = value;
}

// [[Rcpp::export]]
double Leaf__opt_ci___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->opt_ci_;
}
// [[Rcpp::export]]
void Leaf__opt_ci___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->opt_ci_ = value;
}

// [[Rcpp::export]]
double Leaf__E_up___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->E_up_;
}
// [[Rcpp::export]]
void Leaf__E_up___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->E_up_ = value;
}

// [[Rcpp::export]]
double Leaf__assim_max___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->assim_max_;
}
// [[Rcpp::export]]
void Leaf__assim_max___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->assim_max_ = value;
}

// [[Rcpp::export]]
double Leaf__count__get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->count;
}
// [[Rcpp::export]]
void Leaf__count__set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->count = value;
}

// [[Rcpp::export]]
double Leaf__Tleaf___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->Tleaf_;
}
// [[Rcpp::export]]
void Leaf__Tleaf___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->Tleaf_ = value;
}

// [[Rcpp::export]]
double Leaf__electron_transport___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->electron_transport_;
}
// [[Rcpp::export]]
void Leaf__electron_transport___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->electron_transport_ = value;
}

// [[Rcpp::export]]
double Leaf__gamma___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->gamma_;
}
// [[Rcpp::export]]
void Leaf__gamma___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->gamma_ = value;
}

// [[Rcpp::export]]
double Leaf__ko___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->ko_;
}
// [[Rcpp::export]]
void Leaf__ko___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->ko_ = value;
}

// [[Rcpp::export]]
double Leaf__kc___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->kc_;
}
// [[Rcpp::export]]
void Leaf__kc___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->kc_ = value;
}

// [[Rcpp::export]]
double Leaf__km___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->km_;
}
// [[Rcpp::export]]
void Leaf__km___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->km_ = value;
}

// [[Rcpp::export]]
double Leaf__R_d___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->R_d_;
}
// [[Rcpp::export]]
void Leaf__R_d___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->R_d_ = value;
}

// [[Rcpp::export]]
double Leaf__vcmax___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->vcmax_;
}
// [[Rcpp::export]]
void Leaf__vcmax___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->vcmax_ = value;
}

// [[Rcpp::export]]
double Leaf__jmax___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->jmax_;
}
// [[Rcpp::export]]
void Leaf__jmax___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->jmax_ = value;
}

// [[Rcpp::export]]
double Leaf__vcmax_ha___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->vcmax_ha_;
}
// [[Rcpp::export]]
void Leaf__vcmax_ha___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->vcmax_ha_ = value;
}

// [[Rcpp::export]]
double Leaf__vcmax_H_d___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->vcmax_H_d_;
}
// [[Rcpp::export]]
void Leaf__vcmax_H_d___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->vcmax_H_d_ = value;
}

// [[Rcpp::export]]
double Leaf__vcmax_d_S___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->vcmax_d_S_;
}
// [[Rcpp::export]]
void Leaf__vcmax_d_S___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->vcmax_d_S_ = value;
}

// [[Rcpp::export]]
double Leaf__jmax_ha___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->jmax_ha_;
}
// [[Rcpp::export]]
void Leaf__jmax_ha___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->jmax_ha_ = value;
}

// [[Rcpp::export]]
double Leaf__jmax_H_d___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->jmax_H_d_;
}
// [[Rcpp::export]]
void Leaf__jmax_H_d___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->jmax_H_d_ = value;
}

// [[Rcpp::export]]
double Leaf__jmax_d_S___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->jmax_d_S_;
}
// [[Rcpp::export]]
void Leaf__jmax_d_S___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->jmax_d_S_ = value;
}

// [[Rcpp::export]]
double Leaf__gamma_25___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->gamma_25_;
}
// [[Rcpp::export]]
void Leaf__gamma_25___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->gamma_25_ = value;
}

// [[Rcpp::export]]
double Leaf__gamma_ha___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->gamma_ha_;
}
// [[Rcpp::export]]
void Leaf__gamma_ha___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->gamma_ha_ = value;
}

// [[Rcpp::export]]
double Leaf__kc_25___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->kc_25_;
}
// [[Rcpp::export]]
void Leaf__kc_25___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->kc_25_ = value;
}

// [[Rcpp::export]]
double Leaf__kc_ha___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->kc_ha_;
}
// [[Rcpp::export]]
void Leaf__kc_ha___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->kc_ha_ = value;
}

// [[Rcpp::export]]
double Leaf__ko_25___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->ko_25_;
}
// [[Rcpp::export]]
void Leaf__ko_25___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->ko_25_ = value;
}

// [[Rcpp::export]]
double Leaf__ko_ha___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->ko_ha_;
}
// [[Rcpp::export]]
void Leaf__ko_ha___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->ko_ha_ = value;
}

// [[Rcpp::export]]
double Leaf__R_d_25__get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->R_d_25;
}
// [[Rcpp::export]]
void Leaf__R_d_25__set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->R_d_25 = value;
}

// [[Rcpp::export]]
double Leaf__rd_q10_intercept___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->rd_q10_intercept_;
}
// [[Rcpp::export]]
void Leaf__rd_q10_intercept___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->rd_q10_intercept_ = value;
}

// [[Rcpp::export]]
double Leaf__rd_q10_slope___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->rd_q10_slope_;
}
// [[Rcpp::export]]
void Leaf__rd_q10_slope___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->rd_q10_slope_ = value;
}

// [[Rcpp::export]]
double Leaf__PPFD___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->PPFD_;
}
// [[Rcpp::export]]
void Leaf__PPFD___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->PPFD_ = value;
}

// [[Rcpp::export]]
double Leaf__atm_vpd___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->atm_vpd_;
}
// [[Rcpp::export]]
void Leaf__atm_vpd___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->atm_vpd_ = value;
}

// [[Rcpp::export]]
double Leaf__ca___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->ca_;
}
// [[Rcpp::export]]
void Leaf__ca___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->ca_ = value;
}

// [[Rcpp::export]]
double Leaf__leaf_temp___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->leaf_temp_;
}
// [[Rcpp::export]]
void Leaf__leaf_temp___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->leaf_temp_ = value;
}

// [[Rcpp::export]]
double Leaf__atm_o2_kpa___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->atm_o2_kpa_;
}
// [[Rcpp::export]]
void Leaf__atm_o2_kpa___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->atm_o2_kpa_ = value;
}

// [[Rcpp::export]]
double Leaf__atm_kpa___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->atm_kpa_;
}
// [[Rcpp::export]]
void Leaf__atm_kpa___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->atm_kpa_ = value;
}

// [[Rcpp::export]]
double Leaf__leaf_specific_conductance_max___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->leaf_specific_conductance_max_;
}
// [[Rcpp::export]]
void Leaf__leaf_specific_conductance_max___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->leaf_specific_conductance_max_ = value;
}

// [[Rcpp::export]]
std::vector<double> Leaf__soil_depth___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->roots_.soil_depth_;
}
// [[Rcpp::export]]
void Leaf__soil_depth___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, std::vector<double> value) {
  obj_->roots_.soil_depth_ = value;
}

// [[Rcpp::export]]
std::vector<double> Leaf__z_soil_mid___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->roots_.z_soil_mid_;
}
// [[Rcpp::export]]
void Leaf__z_soil_mid___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, std::vector<double> value) {
  obj_->roots_.z_soil_mid_ = value;
}

// [[Rcpp::export]]
double Leaf__dz___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->roots_.dz_;
}
// [[Rcpp::export]]
void Leaf__dz___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->roots_.dz_ = value;
}

// [[Rcpp::export]]
int Leaf__soil_number_of_depths___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->roots_.soil_number_of_depths_;
}
// [[Rcpp::export]]
void Leaf__soil_number_of_depths___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, int value) {
  obj_->roots_.soil_number_of_depths_ = value;
}

// [[Rcpp::export]]
int Leaf__max_soil_layer__get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->roots_.max_soil_layer;
}
// [[Rcpp::export]]
void Leaf__max_soil_layer__set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, int value) {
  obj_->roots_.max_soil_layer = value;
}

// [[Rcpp::export]]
std::vector<double> Leaf__psi_soil___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->roots_.psi_soil_;
}
// [[Rcpp::export]]
void Leaf__psi_soil___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, std::vector<double> value) {
  obj_->roots_.psi_soil_ = value;
}

// [[Rcpp::export]]
std::vector<double> Leaf__c_r_V___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->roots_.network_.c_r_V;
}
// [[Rcpp::export]]
void Leaf__c_r_V___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, std::vector<double> value) {
  obj_->roots_.network_.c_r_V = value;
}

// [[Rcpp::export]]
std::vector<double> Leaf__c_r_H___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->roots_.network_.c_r_H;
}
// [[Rcpp::export]]
void Leaf__c_r_H___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, std::vector<double> value) {
  obj_->roots_.network_.c_r_H = value;
}

// [[Rcpp::export]]
std::vector<double> Leaf__r_R_H_min__get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->roots_.network_.r_R_H_min;
}
// [[Rcpp::export]]
void Leaf__r_R_H_min__set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, std::vector<double> value) {
  obj_->roots_.network_.r_R_H_min = value;
}

// [[Rcpp::export]]
std::vector<double> Leaf__r_R_V__get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->roots_.network_.r_R_V;
}
// [[Rcpp::export]]
void Leaf__r_R_V__set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, std::vector<double> value) {
  obj_->roots_.network_.r_R_V = value;
}

// [[Rcpp::export]]
std::vector<double> Leaf__r_R_V_sum__get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->roots_.network_.r_R_V_sum;
}
// [[Rcpp::export]]
void Leaf__r_R_V_sum__set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, std::vector<double> value) {
  obj_->roots_.network_.r_R_V_sum = value;
}

// [[Rcpp::export]]
std::vector<double> Leaf__f_r__get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->f_r;
}
// [[Rcpp::export]]
void Leaf__f_r__set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, std::vector<double> value) {
  obj_->f_r = value;
}

// [[Rcpp::export]]
bool Leaf__use_energy_balance___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->use_energy_balance_;
}
// [[Rcpp::export]]
void Leaf__use_energy_balance___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, bool value) {
  obj_->use_energy_balance_ = value;
}

// [[Rcpp::export]]
double Leaf__vpd_leaf___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->vpd_leaf_;
}
// [[Rcpp::export]]
void Leaf__vpd_leaf___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->vpd_leaf_ = value;
}

// [[Rcpp::export]]
bool Leaf__use_thermal_cost___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->use_thermal_cost_;
}
// [[Rcpp::export]]
void Leaf__use_thermal_cost___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, bool value) {
  obj_->use_thermal_cost_ = value;
}

// [[Rcpp::export]]
double Leaf__T50___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->T50_;
}
// [[Rcpp::export]]
void Leaf__T50___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->T50_ = value;
}

// [[Rcpp::export]]
double Leaf__Tcrit___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->Tcrit_;
}
// [[Rcpp::export]]
void Leaf__Tcrit___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->Tcrit_ = value;
}

// [[Rcpp::export]]
int Leaf__profitmax_scan_n___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->profitmax_scan_n_;
}
// [[Rcpp::export]]
void Leaf__profitmax_scan_n___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, int value) {
  obj_->profitmax_scan_n_ = value;
}

// [[Rcpp::export]]
int Leaf__boundary_scan_n___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->boundary_scan_n_;
}
// [[Rcpp::export]]
void Leaf__boundary_scan_n___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, int value) {
  obj_->boundary_scan_n_ = value;
}

// [[Rcpp::export]]
double Leaf__d___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->d_;
}
// [[Rcpp::export]]
void Leaf__d___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->d_ = value;
}

// [[Rcpp::export]]
double Leaf__wind_speed___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->wind_speed_;
}
// [[Rcpp::export]]
void Leaf__wind_speed___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->wind_speed_ = value;
}

// [[Rcpp::export]]
double Leaf__Tair___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->Tair_;
}
// [[Rcpp::export]]
void Leaf__Tair___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->Tair_ = value;
}

// [[Rcpp::export]]
double Leaf__Rn___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->Rn_;
}
// [[Rcpp::export]]
void Leaf__Rn___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->Rn_ = value;
}

// [[Rcpp::export]]
double Leaf__ra___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->ra_;
}
// [[Rcpp::export]]
void Leaf__ra___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->ra_ = value;
}

// [[Rcpp::export]]
double Leaf__medlyn_model_gs___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->medlyn_model_gs_;
}
// [[Rcpp::export]]
void Leaf__medlyn_model_gs___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->medlyn_model_gs_ = value;
}

// [[Rcpp::export]]
double Leaf__g0__get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->g0;
}
// [[Rcpp::export]]
void Leaf__g0__set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->g0 = value;
}

// [[Rcpp::export]]
double Leaf__g1__get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->g1;
}
// [[Rcpp::export]]
void Leaf__g1__set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->g1 = value;
}

// [[Rcpp::export]]
double Leaf__theta_w___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->theta_w_;
}
// [[Rcpp::export]]
void Leaf__theta_w___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->theta_w_ = value;
}

// [[Rcpp::export]]
double Leaf__theta_fc___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->theta_fc_;
}
// [[Rcpp::export]]
void Leaf__theta_fc___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->theta_fc_ = value;
}

// [[Rcpp::export]]
double Leaf__theta___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->theta_;
}
// [[Rcpp::export]]
void Leaf__theta___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->theta_ = value;
}

// [[Rcpp::export]]
std::string Leaf__supply_kind__get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->supply_kind_name();
}

// [[Rcpp::export]]
double Leaf__single_resistance___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->single_.resistance_;
}

// [[Rcpp::export]]
double Leaf__single_gravity_head___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->single_.grav_head_;
}

// [[Rcpp::export]]
double Leaf__single_psi_soil___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->single_.psi_soil_;
}

// [[Rcpp::export]]
double Leaf__lambda__get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->marginal_cost_water();
}

// [[Rcpp::export]]
double Leaf__lambda_molar__get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->marginal_cost_water_molar();
}

// [[Rcpp::export]]
double Leaf__lambda_multilayer__get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->marginal_cost_water_multilayer();
}

// [[Rcpp::export]]
double Leaf__profitmax_lambda__get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->profitmax_lambda();
}

// [[Rcpp::export]]
double Leaf__g1_eff__get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->g1_eff();
}

// [[Rcpp::export]]
double Leaf__gs_H2O__get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->stom_cond_H2O();
}

// [[Rcpp::export]]
double Leaf__H2O_CO2_stom_diff_ratio___get(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_) {
  return obj_->H2O_CO2_stom_diff_ratio_;
}
// [[Rcpp::export]]
void Leaf__H2O_CO2_stom_diff_ratio___set(phylloptim::RcppR6::RcppR6<phylloptim::Leaf> obj_, double value) {
  obj_->H2O_CO2_stom_diff_ratio_ = value;
}



