// The root-architecture model, exposed to R.
//
// NOT generated by RcppR6, and not in inst/RcppR6_classes.yml, because it is a
// free function rather than a class member and RcppR6 only generates class glue.
// A plain Rcpp attribute is the whole mechanism.
//
// WHY IT IS EXPOSED AT ALL, given that #33 was about the leaf NOT running this.
// Two reasons, and neither is convenience:
//
//   * The layer thickness. root_network_from_carbon scales the vertical
//     resistance by dz^2, and dz is derived from the soil-depth profile by a rule
//     (phylloptim::layer_thickness) that the leaf applies to the same profile.
//     An R caller who reimplemented it would be one arithmetic slip away from a
//     silent squared factor, so this takes the PROFILE and derives dz itself.
//   * It is what makes the default in set_drivers() honest. The R default root
//     network is a nominal carbon profile put through this function, visibly,
//     rather than five hard-coded resistance vectors whose provenance would rot.
#include <phylloptim.h>

//' Root resistances from a root carbon profile
//'
//' The root-architecture model that used to run inside `set_physiology()` (#33).
//' Each layer's root carbon is split 1/3 vertical : 2/3 horizontal; the minimum
//' horizontal resistance is `beta_R_H / c_r_h`, and the vertical resistance is
//' `beta_R_V * dz^2 / c_r_v`, accumulated from the surface down.
//'
//' The result is sized to the deepest layer with non-zero root carbon, so it is
//' shorter than `soil_depth` for a plant that is shallower than the soil profile.
//' That is what `max_soil_layer` reports after a solve.
//'
//' @section This is a model, not a conversion:
//' The 1/3 : 2/3 split, the `dz^2` scaling and both `beta_R_*` constants are
//' choices, made in plant's TF24 strategy and calibrated there for
//' *Eucalyptus saligna*. Nothing in the leaf solve depends on them -- it reads
//' the resistances. If you have measured root resistances, or are fitting them,
//' build a [RootNetwork()] directly and do not come through here.
//'
//' @param root_carbon_per_leaf_area root carbon **per unit leaf area**, kg C
//'   m^-2 leaf, one entry per soil layer. Per unit leaf area because the leaf is
//'   purely intensive; passing absolute carbon gives resistances that are wrong
//'   by the leaf area and no error anywhere will say so.
//' @param soil_depth cumulative depth to the bottom of each layer, m. The layer
//'   thickness `dz` is derived from it exactly as the leaf derives it, which is
//'   why this takes the profile rather than `dz`.
//' @param beta_R_H proportionality constant between minimum horizontal
//'   (intralayer) root hydraulic resistance and `C_r^-1`
//'   (MPa s mol C / mol H2O).
//' @param beta_R_V proportionality constant between minimum vertical
//'   (interlayer) root hydraulic resistance and `dz^2/C_r`
//'   (MPa mol C s / mol H2O / m^2).
//'
//' @return A [RootNetwork()].
//' @seealso [RootNetwork()], [set_drivers()]
//' @examples
//' root_network_from_carbon(rep(20 / 3, 3), soil_depth = 1:3)
//' @export
// [[Rcpp::export]]
phylloptim::RootNetwork root_network_from_carbon(
    const std::vector<double>& root_carbon_per_leaf_area,
    const std::vector<double>& soil_depth,
    double beta_R_H = 3.4e2,
    double beta_R_V = 9.4e3) {
  if (root_carbon_per_leaf_area.size() != soil_depth.size()) {
    Rcpp::stop("root_carbon_per_leaf_area and soil_depth must have the same "
               "number of elements");
  }
  if (soil_depth.empty()) {
    Rcpp::stop("soil_depth must have at least one layer");
  }
  return phylloptim::root_network_from_carbon(
      root_carbon_per_leaf_area, phylloptim::layer_thickness(soil_depth),
      beta_R_H, beta_R_V);
}
