# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RootNetwork__ctor <- function() {
    .Call('_phylloptim_RootNetwork__ctor', PACKAGE = 'phylloptim')
}

Leaf__ctor <- function(vcmax_25, stem_c, stem_b, psi_crit, root_c, root_b, root_psi_crit, beta2, jmax_25, a, curv_fact_elec_trans, curv_fact_colim, GSS_tol_abs, vulnerability_curve_ncontrol, ci_abs_tol, ci_niter, cost_scale_TF24) {
    .Call('_phylloptim_Leaf__ctor', PACKAGE = 'phylloptim', vcmax_25, stem_c, stem_b, psi_crit, root_c, root_b, root_psi_crit, beta2, jmax_25, a, curv_fact_elec_trans, curv_fact_colim, GSS_tol_abs, vulnerability_curve_ncontrol, ci_abs_tol, ci_niter, cost_scale_TF24)
}

Leaf__operating_point_values <- function(obj_) {
    .Call('_phylloptim_Leaf__operating_point_values', PACKAGE = 'phylloptim', obj_)
}

Leaf__initialize_integrator <- function(obj_, integration_rule, integration_tol) {
    invisible(.Call('_phylloptim_Leaf__initialize_integrator', PACKAGE = 'phylloptim', obj_, integration_rule, integration_tol))
}

Leaf__set_physiology <- function(obj_, root_network, PPFD, psi_soil, soil_depth, leaf_specific_conductance_max, atm_vpd, ca, leaf_temp, atm_o2_kpa, atm_kpa) {
    invisible(.Call('_phylloptim_Leaf__set_physiology', PACKAGE = 'phylloptim', obj_, root_network, PPFD, psi_soil, soil_depth, leaf_specific_conductance_max, atm_vpd, ca, leaf_temp, atm_o2_kpa, atm_kpa))
}

Leaf__perturb_stem_b <- function(obj_, stem_b) {
    invisible(.Call('_phylloptim_Leaf__perturb_stem_b', PACKAGE = 'phylloptim', obj_, stem_b))
}

Leaf__set_traits <- function(obj_, vcmax_25, stem_c, stem_b, psi_crit, root_c, root_b, root_psi_crit, beta2, jmax_25, a, curv_fact_elec_trans, curv_fact_colim, cost_scale_TF24, R_d_25) {
    invisible(.Call('_phylloptim_Leaf__set_traits', PACKAGE = 'phylloptim', obj_, vcmax_25, stem_c, stem_b, psi_crit, root_c, root_b, root_psi_crit, beta2, jmax_25, a, curv_fact_elec_trans, curv_fact_colim, cost_scale_TF24, R_d_25))
}

Leaf__proportion_of_conductivity <- function(obj_, psi) {
    .Call('_phylloptim_Leaf__proportion_of_conductivity', PACKAGE = 'phylloptim', obj_, psi)
}

Leaf__arrh_curve <- function(obj_, Ea, ref_value, leaf_temp) {
    .Call('_phylloptim_Leaf__arrh_curve', PACKAGE = 'phylloptim', obj_, Ea, ref_value, leaf_temp)
}

Leaf__peak_arrh_curve <- function(obj_, Ea, ref_value, leaf_temp, H_d, d_S) {
    .Call('_phylloptim_Leaf__peak_arrh_curve', PACKAGE = 'phylloptim', obj_, Ea, ref_value, leaf_temp, H_d, d_S)
}

Leaf__transpiration <- function(obj_, psi_stem, psi_upstream) {
    .Call('_phylloptim_Leaf__transpiration', PACKAGE = 'phylloptim', obj_, psi_stem, psi_upstream)
}

Leaf__transpiration_full_integration <- function(obj_, psi_stem, psi_upstream) {
    .Call('_phylloptim_Leaf__transpiration_full_integration', PACKAGE = 'phylloptim', obj_, psi_stem, psi_upstream)
}

Leaf__stom_cond_CO2 <- function(obj_, psi_stem, psi_upstream) {
    .Call('_phylloptim_Leaf__stom_cond_CO2', PACKAGE = 'phylloptim', obj_, psi_stem, psi_upstream)
}

Leaf__transpiration_to_psi_stem <- function(obj_, transpiration_, psi_upstream) {
    .Call('_phylloptim_Leaf__transpiration_to_psi_stem', PACKAGE = 'phylloptim', obj_, transpiration_, psi_upstream)
}

Leaf__assim_rubisco_limited <- function(obj_, ci_) {
    .Call('_phylloptim_Leaf__assim_rubisco_limited', PACKAGE = 'phylloptim', obj_, ci_)
}

Leaf__assim_electron_limited <- function(obj_, ci_) {
    .Call('_phylloptim_Leaf__assim_electron_limited', PACKAGE = 'phylloptim', obj_, ci_)
}

Leaf__assim_colimited <- function(obj_, ci_) {
    .Call('_phylloptim_Leaf__assim_colimited', PACKAGE = 'phylloptim', obj_, ci_)
}

Leaf__assim_minus_stom_cond_CO2 <- function(obj_, x, psi_stem, psi_upstream) {
    .Call('_phylloptim_Leaf__assim_minus_stom_cond_CO2', PACKAGE = 'phylloptim', obj_, x, psi_stem, psi_upstream)
}

Leaf__electron_transport <- function(obj_) {
    .Call('_phylloptim_Leaf__electron_transport', PACKAGE = 'phylloptim', obj_)
}

Leaf__leaf_temp_from_E <- function(obj_, E) {
    .Call('_phylloptim_Leaf__leaf_temp_from_E', PACKAGE = 'phylloptim', obj_, E)
}

Leaf__set_leaf_states_rates_from_psi_stem <- function(obj_, psi_stem, psi_upstream) {
    invisible(.Call('_phylloptim_Leaf__set_leaf_states_rates_from_psi_stem', PACKAGE = 'phylloptim', obj_, psi_stem, psi_upstream))
}

Leaf__E_from_Soil_to_Root_Collar <- function(obj_, P_x_r, psi_soil) {
    invisible(.Call('_phylloptim_Leaf__E_from_Soil_to_Root_Collar', PACKAGE = 'phylloptim', obj_, P_x_r, psi_soil))
}

Leaf__find_root_collar_psi <- function(obj_) {
    invisible(.Call('_phylloptim_Leaf__find_root_collar_psi', PACKAGE = 'phylloptim', obj_))
}

Leaf__find_root_psi <- function(obj_, wettest_soil_layer, psi_soil, find_root_crit) {
    .Call('_phylloptim_Leaf__find_root_psi', PACKAGE = 'phylloptim', obj_, wettest_soil_layer, psi_soil, find_root_crit)
}

Leaf__find_psi_stem_from_psi_root <- function(obj_, psi_root, psi_soil) {
    .Call('_phylloptim_Leaf__find_psi_stem_from_psi_root', PACKAGE = 'phylloptim', obj_, psi_root, psi_soil)
}

Leaf__evaluate_root_collar_psi <- function(obj_, target_opt_root_psi) {
    .Call('_phylloptim_Leaf__evaluate_root_collar_psi', PACKAGE = 'phylloptim', obj_, target_opt_root_psi)
}

Leaf__dprofit_droot_collar_psi <- function(obj_, opt_root_psi) {
    .Call('_phylloptim_Leaf__dprofit_droot_collar_psi', PACKAGE = 'phylloptim', obj_, opt_root_psi)
}

Leaf__dprofit_droot_collar_psi_checked <- function(obj_, opt_root_psi) {
    .Call('_phylloptim_Leaf__dprofit_droot_collar_psi_checked', PACKAGE = 'phylloptim', obj_, opt_root_psi)
}

Leaf__psi_stem_to_ci <- function(obj_, psi_stem, psi_upstream) {
    .Call('_phylloptim_Leaf__psi_stem_to_ci', PACKAGE = 'phylloptim', obj_, psi_stem, psi_upstream)
}

Leaf__hydraulic_cost_Sperry <- function(obj_, psi_stem, psi_upstream) {
    .Call('_phylloptim_Leaf__hydraulic_cost_Sperry', PACKAGE = 'phylloptim', obj_, psi_stem, psi_upstream)
}

Leaf__hydraulic_cost_TF <- function(obj_, psi_stem) {
    .Call('_phylloptim_Leaf__hydraulic_cost_TF', PACKAGE = 'phylloptim', obj_, psi_stem)
}

Leaf__profit_psi_stem_Sperry <- function(obj_, psi_stem, psi_upstream) {
    .Call('_phylloptim_Leaf__profit_psi_stem_Sperry', PACKAGE = 'phylloptim', obj_, psi_stem, psi_upstream)
}

Leaf__profit_psi_stem_TF <- function(obj_, psi_stem, psi_upstream) {
    .Call('_phylloptim_Leaf__profit_psi_stem_TF', PACKAGE = 'phylloptim', obj_, psi_stem, psi_upstream)
}

Leaf__lambda_TF24 <- function(obj_, psi_stem) {
    .Call('_phylloptim_Leaf__lambda_TF24', PACKAGE = 'phylloptim', obj_, psi_stem)
}

Leaf__optimise_psi_stem_Sperry <- function(obj_) {
    invisible(.Call('_phylloptim_Leaf__optimise_psi_stem_Sperry', PACKAGE = 'phylloptim', obj_))
}

Leaf__thermal_cost_at <- function(obj_, leaf_temp) {
    .Call('_phylloptim_Leaf__thermal_cost_at', PACKAGE = 'phylloptim', obj_, leaf_temp)
}

Leaf__prepare_profitmax <- function(obj_) {
    invisible(.Call('_phylloptim_Leaf__prepare_profitmax', PACKAGE = 'phylloptim', obj_))
}

Leaf__profit_psi_stem_ProfitMax <- function(obj_, psi_stem, psi_upstream) {
    .Call('_phylloptim_Leaf__profit_psi_stem_ProfitMax', PACKAGE = 'phylloptim', obj_, psi_stem, psi_upstream)
}

Leaf__profitmax_curve <- function(obj_, n) {
    .Call('_phylloptim_Leaf__profitmax_curve', PACKAGE = 'phylloptim', obj_, n)
}

Leaf__optimise_psi_stem_ProfitMax <- function(obj_) {
    invisible(.Call('_phylloptim_Leaf__optimise_psi_stem_ProfitMax', PACKAGE = 'phylloptim', obj_))
}

Leaf__optimise_psi_stem_TF <- function(obj_) {
    invisible(.Call('_phylloptim_Leaf__optimise_psi_stem_TF', PACKAGE = 'phylloptim', obj_))
}

Leaf__medlyn_model_gs <- function(obj_, assim_colimited_) {
    .Call('_phylloptim_Leaf__medlyn_model_gs', PACKAGE = 'phylloptim', obj_, assim_colimited_)
}

Leaf__solve_medlyn_ci_numerical <- function(obj_) {
    invisible(.Call('_phylloptim_Leaf__solve_medlyn_ci_numerical', PACKAGE = 'phylloptim', obj_))
}

Leaf__solve_medlyn_ci_analytical <- function(obj_) {
    invisible(.Call('_phylloptim_Leaf__solve_medlyn_ci_analytical', PACKAGE = 'phylloptim', obj_))
}

Leaf__set_supply_multilayer <- function(obj_) {
    invisible(.Call('_phylloptim_Leaf__set_supply_multilayer', PACKAGE = 'phylloptim', obj_))
}

Leaf__set_supply_single <- function(obj_, gravity_head) {
    invisible(.Call('_phylloptim_Leaf__set_supply_single', PACKAGE = 'phylloptim', obj_, gravity_head))
}

Leaf__setup_transpiration <- function(obj_, resolution) {
    invisible(.Call('_phylloptim_Leaf__setup_transpiration', PACKAGE = 'phylloptim', obj_, resolution))
}

Leaf__setup_root_vulnerability <- function(obj_, resolution) {
    invisible(.Call('_phylloptim_Leaf__setup_root_vulnerability', PACKAGE = 'phylloptim', obj_, resolution))
}

Leaf__vcmax_25__get <- function(obj_) {
    .Call('_phylloptim_Leaf__vcmax_25__get', PACKAGE = 'phylloptim', obj_)
}

Leaf__jmax_25__get <- function(obj_) {
    .Call('_phylloptim_Leaf__jmax_25__get', PACKAGE = 'phylloptim', obj_)
}

Leaf__stem_c__get <- function(obj_) {
    .Call('_phylloptim_Leaf__stem_c__get', PACKAGE = 'phylloptim', obj_)
}

Leaf__stem_b__get <- function(obj_) {
    .Call('_phylloptim_Leaf__stem_b__get', PACKAGE = 'phylloptim', obj_)
}

Leaf__psi_crit__get <- function(obj_) {
    .Call('_phylloptim_Leaf__psi_crit__get', PACKAGE = 'phylloptim', obj_)
}

Leaf__root_c__get <- function(obj_) {
    .Call('_phylloptim_Leaf__root_c__get', PACKAGE = 'phylloptim', obj_)
}

Leaf__root_b__get <- function(obj_) {
    .Call('_phylloptim_Leaf__root_b__get', PACKAGE = 'phylloptim', obj_)
}

Leaf__root_psi_crit__get <- function(obj_) {
    .Call('_phylloptim_Leaf__root_psi_crit__get', PACKAGE = 'phylloptim', obj_)
}

Leaf__beta2__get <- function(obj_) {
    .Call('_phylloptim_Leaf__beta2__get', PACKAGE = 'phylloptim', obj_)
}

Leaf__a__get <- function(obj_) {
    .Call('_phylloptim_Leaf__a__get', PACKAGE = 'phylloptim', obj_)
}

Leaf__curv_fact_elec_trans__get <- function(obj_) {
    .Call('_phylloptim_Leaf__curv_fact_elec_trans__get', PACKAGE = 'phylloptim', obj_)
}

Leaf__curv_fact_colim__get <- function(obj_) {
    .Call('_phylloptim_Leaf__curv_fact_colim__get', PACKAGE = 'phylloptim', obj_)
}

Leaf__cost_scale_TF24__get <- function(obj_) {
    .Call('_phylloptim_Leaf__cost_scale_TF24__get', PACKAGE = 'phylloptim', obj_)
}

Leaf__ci___get <- function(obj_) {
    .Call('_phylloptim_Leaf__ci___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__ci___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__ci___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__stom_cond_CO2___get <- function(obj_) {
    .Call('_phylloptim_Leaf__stom_cond_CO2___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__stom_cond_CO2___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__stom_cond_CO2___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__assim_colimited___get <- function(obj_) {
    .Call('_phylloptim_Leaf__assim_colimited___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__assim_colimited___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__assim_colimited___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__transpiration___get <- function(obj_) {
    .Call('_phylloptim_Leaf__transpiration___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__transpiration___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__transpiration___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__soil_consumption___get <- function(obj_) {
    .Call('_phylloptim_Leaf__soil_consumption___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__soil_consumption___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__soil_consumption___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__profit___get <- function(obj_) {
    .Call('_phylloptim_Leaf__profit___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__profit___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__profit___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__psi_stem__get <- function(obj_) {
    .Call('_phylloptim_Leaf__psi_stem__get', PACKAGE = 'phylloptim', obj_)
}

Leaf__psi_stem__set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__psi_stem__set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__lambda___get <- function(obj_) {
    .Call('_phylloptim_Leaf__lambda___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__lambda___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__lambda___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__carbon_gain___get <- function(obj_) {
    .Call('_phylloptim_Leaf__carbon_gain___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__carbon_gain___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__carbon_gain___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__hydraulic_cost_norm___get <- function(obj_) {
    .Call('_phylloptim_Leaf__hydraulic_cost_norm___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__hydraulic_cost_norm___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__hydraulic_cost_norm___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__thermal_cost___get <- function(obj_) {
    .Call('_phylloptim_Leaf__thermal_cost___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__thermal_cost___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__thermal_cost___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__hydraulic_cost___get <- function(obj_) {
    .Call('_phylloptim_Leaf__hydraulic_cost___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__hydraulic_cost___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__hydraulic_cost___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__opt_psi_stem___get <- function(obj_) {
    .Call('_phylloptim_Leaf__opt_psi_stem___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__opt_psi_stem___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__opt_psi_stem___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__opt_root_psi___get <- function(obj_) {
    .Call('_phylloptim_Leaf__opt_root_psi___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__opt_root_psi___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__opt_root_psi___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__opt_ci___get <- function(obj_) {
    .Call('_phylloptim_Leaf__opt_ci___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__opt_ci___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__opt_ci___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__E_up___get <- function(obj_) {
    .Call('_phylloptim_Leaf__E_up___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__E_up___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__E_up___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__assim_max___get <- function(obj_) {
    .Call('_phylloptim_Leaf__assim_max___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__assim_max___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__assim_max___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__count__get <- function(obj_) {
    .Call('_phylloptim_Leaf__count__get', PACKAGE = 'phylloptim', obj_)
}

Leaf__count__set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__count__set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__Tleaf___get <- function(obj_) {
    .Call('_phylloptim_Leaf__Tleaf___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__Tleaf___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__Tleaf___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__electron_transport___get <- function(obj_) {
    .Call('_phylloptim_Leaf__electron_transport___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__electron_transport___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__electron_transport___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__gamma___get <- function(obj_) {
    .Call('_phylloptim_Leaf__gamma___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__gamma___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__gamma___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__ko___get <- function(obj_) {
    .Call('_phylloptim_Leaf__ko___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__ko___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__ko___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__kc___get <- function(obj_) {
    .Call('_phylloptim_Leaf__kc___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__kc___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__kc___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__km___get <- function(obj_) {
    .Call('_phylloptim_Leaf__km___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__km___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__km___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__R_d___get <- function(obj_) {
    .Call('_phylloptim_Leaf__R_d___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__R_d___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__R_d___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__vcmax___get <- function(obj_) {
    .Call('_phylloptim_Leaf__vcmax___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__vcmax___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__vcmax___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__jmax___get <- function(obj_) {
    .Call('_phylloptim_Leaf__jmax___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__jmax___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__jmax___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__vcmax_ha___get <- function(obj_) {
    .Call('_phylloptim_Leaf__vcmax_ha___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__vcmax_ha___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__vcmax_ha___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__vcmax_H_d___get <- function(obj_) {
    .Call('_phylloptim_Leaf__vcmax_H_d___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__vcmax_H_d___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__vcmax_H_d___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__vcmax_d_S___get <- function(obj_) {
    .Call('_phylloptim_Leaf__vcmax_d_S___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__vcmax_d_S___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__vcmax_d_S___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__jmax_ha___get <- function(obj_) {
    .Call('_phylloptim_Leaf__jmax_ha___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__jmax_ha___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__jmax_ha___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__jmax_H_d___get <- function(obj_) {
    .Call('_phylloptim_Leaf__jmax_H_d___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__jmax_H_d___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__jmax_H_d___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__jmax_d_S___get <- function(obj_) {
    .Call('_phylloptim_Leaf__jmax_d_S___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__jmax_d_S___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__jmax_d_S___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__gamma_25___get <- function(obj_) {
    .Call('_phylloptim_Leaf__gamma_25___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__gamma_25___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__gamma_25___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__gamma_ha___get <- function(obj_) {
    .Call('_phylloptim_Leaf__gamma_ha___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__gamma_ha___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__gamma_ha___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__kc_25___get <- function(obj_) {
    .Call('_phylloptim_Leaf__kc_25___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__kc_25___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__kc_25___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__kc_ha___get <- function(obj_) {
    .Call('_phylloptim_Leaf__kc_ha___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__kc_ha___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__kc_ha___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__ko_25___get <- function(obj_) {
    .Call('_phylloptim_Leaf__ko_25___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__ko_25___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__ko_25___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__ko_ha___get <- function(obj_) {
    .Call('_phylloptim_Leaf__ko_ha___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__ko_ha___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__ko_ha___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__R_d_25__get <- function(obj_) {
    .Call('_phylloptim_Leaf__R_d_25__get', PACKAGE = 'phylloptim', obj_)
}

Leaf__R_d_25__set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__R_d_25__set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__rd_q10_intercept___get <- function(obj_) {
    .Call('_phylloptim_Leaf__rd_q10_intercept___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__rd_q10_intercept___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__rd_q10_intercept___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__rd_q10_slope___get <- function(obj_) {
    .Call('_phylloptim_Leaf__rd_q10_slope___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__rd_q10_slope___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__rd_q10_slope___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__PPFD___get <- function(obj_) {
    .Call('_phylloptim_Leaf__PPFD___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__PPFD___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__PPFD___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__atm_vpd___get <- function(obj_) {
    .Call('_phylloptim_Leaf__atm_vpd___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__atm_vpd___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__atm_vpd___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__ca___get <- function(obj_) {
    .Call('_phylloptim_Leaf__ca___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__ca___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__ca___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__leaf_temp___get <- function(obj_) {
    .Call('_phylloptim_Leaf__leaf_temp___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__leaf_temp___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__leaf_temp___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__atm_o2_kpa___get <- function(obj_) {
    .Call('_phylloptim_Leaf__atm_o2_kpa___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__atm_o2_kpa___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__atm_o2_kpa___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__atm_kpa___get <- function(obj_) {
    .Call('_phylloptim_Leaf__atm_kpa___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__atm_kpa___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__atm_kpa___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__leaf_specific_conductance_max___get <- function(obj_) {
    .Call('_phylloptim_Leaf__leaf_specific_conductance_max___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__leaf_specific_conductance_max___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__leaf_specific_conductance_max___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__soil_depth___get <- function(obj_) {
    .Call('_phylloptim_Leaf__soil_depth___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__soil_depth___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__soil_depth___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__z_soil_mid___get <- function(obj_) {
    .Call('_phylloptim_Leaf__z_soil_mid___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__z_soil_mid___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__z_soil_mid___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__dz___get <- function(obj_) {
    .Call('_phylloptim_Leaf__dz___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__dz___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__dz___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__soil_number_of_depths___get <- function(obj_) {
    .Call('_phylloptim_Leaf__soil_number_of_depths___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__soil_number_of_depths___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__soil_number_of_depths___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__max_soil_layer__get <- function(obj_) {
    .Call('_phylloptim_Leaf__max_soil_layer__get', PACKAGE = 'phylloptim', obj_)
}

Leaf__max_soil_layer__set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__max_soil_layer__set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__psi_soil___get <- function(obj_) {
    .Call('_phylloptim_Leaf__psi_soil___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__psi_soil___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__psi_soil___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__c_r_V___get <- function(obj_) {
    .Call('_phylloptim_Leaf__c_r_V___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__c_r_V___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__c_r_V___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__c_r_H___get <- function(obj_) {
    .Call('_phylloptim_Leaf__c_r_H___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__c_r_H___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__c_r_H___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__r_R_H_min__get <- function(obj_) {
    .Call('_phylloptim_Leaf__r_R_H_min__get', PACKAGE = 'phylloptim', obj_)
}

Leaf__r_R_H_min__set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__r_R_H_min__set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__r_R_V__get <- function(obj_) {
    .Call('_phylloptim_Leaf__r_R_V__get', PACKAGE = 'phylloptim', obj_)
}

Leaf__r_R_V__set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__r_R_V__set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__r_R_V_sum__get <- function(obj_) {
    .Call('_phylloptim_Leaf__r_R_V_sum__get', PACKAGE = 'phylloptim', obj_)
}

Leaf__r_R_V_sum__set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__r_R_V_sum__set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__f_r__get <- function(obj_) {
    .Call('_phylloptim_Leaf__f_r__get', PACKAGE = 'phylloptim', obj_)
}

Leaf__f_r__set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__f_r__set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__use_energy_balance___get <- function(obj_) {
    .Call('_phylloptim_Leaf__use_energy_balance___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__use_energy_balance___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__use_energy_balance___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__vpd_leaf___get <- function(obj_) {
    .Call('_phylloptim_Leaf__vpd_leaf___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__vpd_leaf___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__vpd_leaf___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__use_thermal_cost___get <- function(obj_) {
    .Call('_phylloptim_Leaf__use_thermal_cost___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__use_thermal_cost___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__use_thermal_cost___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__T50___get <- function(obj_) {
    .Call('_phylloptim_Leaf__T50___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__T50___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__T50___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__Tcrit___get <- function(obj_) {
    .Call('_phylloptim_Leaf__Tcrit___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__Tcrit___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__Tcrit___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__profitmax_scan_n___get <- function(obj_) {
    .Call('_phylloptim_Leaf__profitmax_scan_n___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__profitmax_scan_n___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__profitmax_scan_n___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__boundary_scan_n___get <- function(obj_) {
    .Call('_phylloptim_Leaf__boundary_scan_n___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__boundary_scan_n___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__boundary_scan_n___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__d___get <- function(obj_) {
    .Call('_phylloptim_Leaf__d___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__d___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__d___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__wind_speed___get <- function(obj_) {
    .Call('_phylloptim_Leaf__wind_speed___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__wind_speed___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__wind_speed___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__Tair___get <- function(obj_) {
    .Call('_phylloptim_Leaf__Tair___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__Tair___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__Tair___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__Rn___get <- function(obj_) {
    .Call('_phylloptim_Leaf__Rn___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__Rn___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__Rn___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__ra___get <- function(obj_) {
    .Call('_phylloptim_Leaf__ra___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__ra___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__ra___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__medlyn_model_gs___get <- function(obj_) {
    .Call('_phylloptim_Leaf__medlyn_model_gs___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__medlyn_model_gs___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__medlyn_model_gs___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__g0__get <- function(obj_) {
    .Call('_phylloptim_Leaf__g0__get', PACKAGE = 'phylloptim', obj_)
}

Leaf__g0__set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__g0__set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__g1__get <- function(obj_) {
    .Call('_phylloptim_Leaf__g1__get', PACKAGE = 'phylloptim', obj_)
}

Leaf__g1__set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__g1__set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__theta_w___get <- function(obj_) {
    .Call('_phylloptim_Leaf__theta_w___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__theta_w___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__theta_w___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__theta_fc___get <- function(obj_) {
    .Call('_phylloptim_Leaf__theta_fc___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__theta_fc___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__theta_fc___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__theta___get <- function(obj_) {
    .Call('_phylloptim_Leaf__theta___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__theta___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__theta___set', PACKAGE = 'phylloptim', obj_, value))
}

Leaf__supply_kind__get <- function(obj_) {
    .Call('_phylloptim_Leaf__supply_kind__get', PACKAGE = 'phylloptim', obj_)
}

Leaf__single_resistance___get <- function(obj_) {
    .Call('_phylloptim_Leaf__single_resistance___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__single_gravity_head___get <- function(obj_) {
    .Call('_phylloptim_Leaf__single_gravity_head___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__single_psi_soil___get <- function(obj_) {
    .Call('_phylloptim_Leaf__single_psi_soil___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__lambda__get <- function(obj_) {
    .Call('_phylloptim_Leaf__lambda__get', PACKAGE = 'phylloptim', obj_)
}

Leaf__lambda_molar__get <- function(obj_) {
    .Call('_phylloptim_Leaf__lambda_molar__get', PACKAGE = 'phylloptim', obj_)
}

Leaf__lambda_multilayer__get <- function(obj_) {
    .Call('_phylloptim_Leaf__lambda_multilayer__get', PACKAGE = 'phylloptim', obj_)
}

Leaf__g1_eff__get <- function(obj_) {
    .Call('_phylloptim_Leaf__g1_eff__get', PACKAGE = 'phylloptim', obj_)
}

Leaf__gs_H2O__get <- function(obj_) {
    .Call('_phylloptim_Leaf__gs_H2O__get', PACKAGE = 'phylloptim', obj_)
}

Leaf__H2O_CO2_stom_diff_ratio___get <- function(obj_) {
    .Call('_phylloptim_Leaf__H2O_CO2_stom_diff_ratio___get', PACKAGE = 'phylloptim', obj_)
}

Leaf__H2O_CO2_stom_diff_ratio___set <- function(obj_, value) {
    invisible(.Call('_phylloptim_Leaf__H2O_CO2_stom_diff_ratio___set', PACKAGE = 'phylloptim', obj_, value))
}

#' The differentiable parameters, in the order C++ indexes them
#'
#' The fourteen [leaf_traits()] in `set_traits()`'s argument order, then
#' `leaf_specific_conductance_max` and `resistance`. Exported so that R's own
#' copy of this order can be compared against it in a test: R passes integer
#' positions into this enumeration, so appending to it is safe and reordering it
#' would silently differentiate the wrong parameter.
#'
#' @return A character vector of sixteen names.
#' @seealso [leaf_gradient_batch()]
#' @examples
#' gradient_par_names()
#' @export
gradient_par_names <- function() {
    .Call('_phylloptim_gradient_par_names', PACKAGE = 'phylloptim')
}

#' The differentiated outputs, in the order C++ indexes them
#'
#' `A`, `gc`, `psi_stem`, `collar` and `profit`. Unlike [gradient_par_names()],
#' which R holds its own copy of and a test compares, R **reads** this one — so
#' the list exists once and adding an output is one edit rather than two that
#' can disagree.
#'
#' The first four are what a gas-exchange calibration observes; `profit` is what
#' a demographic consumer bills, and it is the one output the envelope theorem
#' reaches. See [leaf_gradient()].
#'
#' @return A character vector of five names.
#' @seealso [leaf_gradient()], [leaf_gradient_batch()]
#' @examples
#' gradient_output_names()
#' @export
gradient_output_names <- function() {
    .Call('_phylloptim_gradient_output_names', PACKAGE = 'phylloptim')
}

gradient_batch_prepare <- function(root_network, psi_soil, soil_depth, PPFD, atm_vpd, ca, leaf_temp, atm_o2_kpa, atm_kpa) {
    .Call('_phylloptim_gradient_batch_prepare', PACKAGE = 'phylloptim', root_network, psi_soil, soil_depth, PPFD, atm_vpd, ca, leaf_temp, atm_o2_kpa, atm_kpa)
}

gradient_batch_check <- function(drivers) {
    invisible(.Call('_phylloptim_gradient_batch_check', PACKAGE = 'phylloptim', drivers))
}

gradient_batch_run <- function(obj_, drivers, theta, pars, step, stationarity_tol, method, fast_stem_curve, psi, dpsi_dtheta) {
    .Call('_phylloptim_gradient_batch_run', PACKAGE = 'phylloptim', obj_, drivers, theta, pars, step, stationarity_tol, method, fast_stem_curve, psi, dpsi_dtheta)
}

#' Root resistances from a root carbon profile
#'
#' The root-architecture model that used to run inside `set_physiology()` (#33).
#' Each layer's root carbon is split 1/3 vertical : 2/3 horizontal; the minimum
#' horizontal resistance is `beta_R_H / c_r_h`, and the vertical resistance is
#' `beta_R_V * dz^2 / c_r_v`, accumulated from the surface down.
#'
#' The result is sized to the deepest layer with non-zero root carbon, so it is
#' shorter than `soil_depth` for a plant that is shallower than the soil profile.
#' That is what `max_soil_layer` reports after a solve.
#'
#' @section This is a model, not a conversion:
#' The 1/3 : 2/3 split, the `dz^2` scaling and both `beta_R_*` constants are
#' choices, made in plant's TF24 strategy and calibrated there for
#' *Eucalyptus saligna*. Nothing in the leaf solve depends on them -- it reads
#' the resistances. If you have measured root resistances, or are fitting them,
#' build a [RootNetwork()] directly and do not come through here.
#'
#' @param root_carbon_per_leaf_area root carbon **per unit leaf area**, kg C
#'   m^-2 leaf, one entry per soil layer. Per unit leaf area because the leaf is
#'   purely intensive; passing absolute carbon gives resistances that are wrong
#'   by the leaf area and no error anywhere will say so.
#' @param soil_depth cumulative depth to the bottom of each layer, m. The layer
#'   thickness `dz` is derived from it exactly as the leaf derives it, which is
#'   why this takes the profile rather than `dz`.
#' @param beta_R_H proportionality constant between minimum horizontal
#'   (intralayer) root hydraulic resistance and `C_r^-1`
#'   (MPa s mol C / mol H2O).
#' @param beta_R_V proportionality constant between minimum vertical
#'   (interlayer) root hydraulic resistance and `dz^2/C_r`
#'   (MPa mol C s / mol H2O / m^2).
#'
#' @return A [RootNetwork()].
#' @seealso [RootNetwork()], [set_drivers()]
#' @examples
#' root_network_from_carbon(rep(20 / 3, 3), soil_depth = 1:3)
#' @export
root_network_from_carbon <- function(root_carbon_per_leaf_area, soil_depth, beta_R_H = 3.4e2, beta_R_V = 9.4e3) {
    .Call('_phylloptim_root_network_from_carbon', PACKAGE = 'phylloptim', root_carbon_per_leaf_area, soil_depth, beta_R_H, beta_R_V)
}

