## Generated by RcppR6: do not edit by hand
## Version: 0.2.4
## Hash: c13a2bbe0d2a3b6d1546028b5f269f96

##' @importFrom Rcpp evalCpp
##' @importFrom R6 R6Class
##' @useDynLib phylloptim
NULL

##' Root hydraulic resistances, per layer and per unit leaf area
##' 
##' What `set_physiology()` takes in place of a root carbon profile (#33). Which
##' root-architecture model turned carbon into these resistances is not this
##' package's business, exactly as which conductance-versus-height model produced
##' `leaf_specific_conductance_max` never was. If you do have a carbon profile,
##' [root_network_from_carbon()] is the model that used to run inside the leaf.
##' 
##' `r_R_H_min` and `r_R_V_sum` are the two fields the solve reads. Their common
##' length is the number of ROOTED layers, which may be fewer than the number of
##' soil layers but never more. `c_r_V`, `c_r_H` and `r_R_V` are diagnostics and
##' may be left empty.
##' 
##' @title Root resistance network
##' @param ...,values Values to initialise the struct with (either as
##' variadic arguments, or as a list, but not both).
##' @export
`RootNetwork` <- function(..., values=list(...)) {
  ret <- RootNetwork__ctor()
  if (length(values) > 0L) {
    if (is.null(names(values)) || any(names(values) == "")) {
      stop("All values must be named")
    }
    if (length(err <- setdiff(names(values), names(ret))) > 0L) {
      stop(sprintf("Unknown fields: %s", paste(err, collapse=", ")))
    }
    to_set <- intersect(names(values), names(ret))
    ret[to_set] <- values[to_set]
  }
  ret
}

##' Leaf-level gas exchange with explicit hydraulics.
##' 
##' Stomatal behaviour emerges from a gain-risk profit maximisation over the
##' root-collar water potential rather than from an empirical conductance
##' model, coupled to Farquhar-von Caemmerer-Berry photosynthesis and an
##' explicit soil-root-stem-leaf water transport path. See the package README
##' for the model and for how it differs from `plantecophys`, `tealeaves` and
##' `bigleaf`.
##' 
##' Set the drivers with `$set_physiology()`, solve with
##' `$find_root_collar_psi()`, then read the operating point off the object:
##' `$opt_psi_stem_`, `$profit_`, `$assim_colimited_`, `$transpiration_`,
##' `$lambda`, `$g1_eff`.
##' 
##' A second optimality formulation is available on the single-soil-layer
##' supply path: `$optimise_psi_stem_ProfitMax()` maximises Sperry (2017)'s
##' normalised profit, and `$profitmax_curve()` returns the whole cost, gain
##' and profit curve in one call. `$optimise_psi_stem_TF()` runs the TF24 cost
##' through the same solver, so the two can be compared at identical drivers.
##' These write `$carbon_gain_`, `$hydraulic_cost_norm_` and `$thermal_cost_`,
##' which are unitless and are NOT the same quantities as `$hydraulic_cost_`.
##' 
##' All water potentials are **positive magnitudes in MPa**. There is one
##' representation throughout and it is asserted, not documented: a negative
##' `psi_crit`, `stem_b`, `root_b` or `root_psi_crit` is an error here, and a
##' negative `psi_soil` is an error in `set_physiology`.
##' 
##' @param vcmax_25 maximum carboxylation rate at 25 C (umol m^-2 s^-1)
##' @param stem_c shape parameter of the STEM hydraulic vulnerability curve (unitless)
##' @param stem_b sensitivity parameter of the STEM hydraulic vulnerability curve (MPa)
##' @param psi_crit critical stem water potential (MPa, positive magnitude)
##' @param root_c shape parameter of the ROOT hydraulic vulnerability curve (unitless)
##' @param root_b sensitivity parameter of the ROOT hydraulic vulnerability curve (MPa)
##' @param root_psi_crit critical root water potential (MPa, positive magnitude)
##' @param beta2 exponent for the effect of hydraulic risk (unitless)
##' @param jmax_25 maximum rate of electron transport at 25 C (umol m^-2 s^-1)
##' @param a quantum yield of photosynthetic electron transport (mol mol^-1)
##' @param curv_fact_elec_trans curvature factor for the light response curve (unitless)
##' @param curv_fact_colim curvature factor for the colimited photosynthesis equation
##' @param GSS_tol_abs absolute tolerance for the golden-section search
##' @param vulnerability_curve_ncontrol number of control points for the pre-computed vulnerability curves
##' @param ci_abs_tol absolute tolerance for root-solving ci
##' @param ci_niter maximum number of iterations for root-solving ci
##' @param cost_scale_TF24 cost parameter for the TF24 profit model (umol m^-2 s^-1)
##' 
##' @export
`Leaf` <- function(vcmax_25, stem_c, stem_b, psi_crit, root_c, root_b, root_psi_crit, beta2, jmax_25, a, curv_fact_elec_trans, curv_fact_colim, GSS_tol_abs, vulnerability_curve_ncontrol, ci_abs_tol, ci_niter, cost_scale_TF24) {
  Leaf__ctor(vcmax_25, stem_c, stem_b, psi_crit, root_c, root_b, root_psi_crit, beta2, jmax_25, a, curv_fact_elec_trans, curv_fact_colim, GSS_tol_abs, vulnerability_curve_ncontrol, ci_abs_tol, ci_niter, cost_scale_TF24)
}
.R6_Leaf <-
  R6::R6Class(
    "Leaf",
    inherit=,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      },
      operating_point_values = function() {
        Leaf__operating_point_values(self)
      },
      initialize_integrator = function(integration_rule, integration_tol) {
        Leaf__initialize_integrator(self, integration_rule, integration_tol)
      },
      set_physiology = function(root_network, PPFD, psi_soil, soil_depth, leaf_specific_conductance_max, atm_vpd, ca, leaf_temp, atm_o2_kpa, atm_kpa) {
        Leaf__set_physiology(self, root_network, PPFD, psi_soil, soil_depth, leaf_specific_conductance_max, atm_vpd, ca, leaf_temp, atm_o2_kpa, atm_kpa)
      },
      perturb_stem_b = function(stem_b) {
        Leaf__perturb_stem_b(self, stem_b)
      },
      set_traits = function(vcmax_25, stem_c, stem_b, psi_crit, root_c, root_b, root_psi_crit, beta2, jmax_25, a, curv_fact_elec_trans, curv_fact_colim, cost_scale_TF24, R_d_25) {
        Leaf__set_traits(self, vcmax_25, stem_c, stem_b, psi_crit, root_c, root_b, root_psi_crit, beta2, jmax_25, a, curv_fact_elec_trans, curv_fact_colim, cost_scale_TF24, R_d_25)
      },
      proportion_of_conductivity = function(psi) {
        Leaf__proportion_of_conductivity(self, psi)
      },
      arrh_curve = function(Ea, ref_value, leaf_temp) {
        Leaf__arrh_curve(self, Ea, ref_value, leaf_temp)
      },
      peak_arrh_curve = function(Ea, ref_value, leaf_temp, H_d, d_S) {
        Leaf__peak_arrh_curve(self, Ea, ref_value, leaf_temp, H_d, d_S)
      },
      transpiration = function(psi_stem, psi_upstream) {
        Leaf__transpiration(self, psi_stem, psi_upstream)
      },
      transpiration_full_integration = function(psi_stem, psi_upstream) {
        Leaf__transpiration_full_integration(self, psi_stem, psi_upstream)
      },
      stom_cond_CO2 = function(psi_stem, psi_upstream) {
        Leaf__stom_cond_CO2(self, psi_stem, psi_upstream)
      },
      transpiration_to_psi_stem = function(transpiration_, psi_upstream) {
        Leaf__transpiration_to_psi_stem(self, transpiration_, psi_upstream)
      },
      assim_rubisco_limited = function(ci_) {
        Leaf__assim_rubisco_limited(self, ci_)
      },
      assim_electron_limited = function(ci_) {
        Leaf__assim_electron_limited(self, ci_)
      },
      assim_colimited = function(ci_) {
        Leaf__assim_colimited(self, ci_)
      },
      assim_minus_stom_cond_CO2 = function(x, psi_stem, psi_upstream) {
        Leaf__assim_minus_stom_cond_CO2(self, x, psi_stem, psi_upstream)
      },
      electron_transport = function() {
        Leaf__electron_transport(self)
      },
      leaf_temp_from_E = function(E) {
        Leaf__leaf_temp_from_E(self, E)
      },
      set_leaf_states_rates_from_psi_stem = function(psi_stem, psi_upstream) {
        Leaf__set_leaf_states_rates_from_psi_stem(self, psi_stem, psi_upstream)
      },
      E_from_Soil_to_Root_Collar = function(P_x_r, psi_soil) {
        Leaf__E_from_Soil_to_Root_Collar(self, P_x_r, psi_soil)
      },
      find_root_collar_psi = function() {
        Leaf__find_root_collar_psi(self)
      },
      find_root_psi = function(wettest_soil_layer, psi_soil, find_root_crit) {
        Leaf__find_root_psi(self, wettest_soil_layer, psi_soil, find_root_crit)
      },
      find_psi_stem_from_psi_root = function(psi_root, psi_soil) {
        Leaf__find_psi_stem_from_psi_root(self, psi_root, psi_soil)
      },
      evaluate_root_collar_psi = function(target_opt_root_psi) {
        Leaf__evaluate_root_collar_psi(self, target_opt_root_psi)
      },
      dprofit_droot_collar_psi = function(opt_root_psi) {
        Leaf__dprofit_droot_collar_psi(self, opt_root_psi)
      },
      dprofit_droot_collar_psi_checked = function(opt_root_psi) {
        Leaf__dprofit_droot_collar_psi_checked(self, opt_root_psi)
      },
      psi_stem_to_ci = function(psi_stem, psi_upstream) {
        Leaf__psi_stem_to_ci(self, psi_stem, psi_upstream)
      },
      hydraulic_cost_TF = function(psi_stem) {
        Leaf__hydraulic_cost_TF(self, psi_stem)
      },
      hydraulic_cost_CowanFarquhar = function(psi_stem, psi_upstream) {
        Leaf__hydraulic_cost_CowanFarquhar(self, psi_stem, psi_upstream)
      },
      profit_psi_stem_TF = function(psi_stem, psi_upstream) {
        Leaf__profit_psi_stem_TF(self, psi_stem, psi_upstream)
      },
      profit_psi_stem_CowanFarquhar = function(psi_stem, psi_upstream) {
        Leaf__profit_psi_stem_CowanFarquhar(self, psi_stem, psi_upstream)
      },
      lambda_TF24 = function(psi_stem) {
        Leaf__lambda_TF24(self, psi_stem)
      },
      optimise_psi_stem_CowanFarquhar = function() {
        Leaf__optimise_psi_stem_CowanFarquhar(self)
      },
      thermal_cost_at = function(leaf_temp) {
        Leaf__thermal_cost_at(self, leaf_temp)
      },
      prepare_profitmax = function() {
        Leaf__prepare_profitmax(self)
      },
      profit_psi_stem_ProfitMax = function(psi_stem, psi_upstream) {
        Leaf__profit_psi_stem_ProfitMax(self, psi_stem, psi_upstream)
      },
      profitmax_curve = function(n) {
        Leaf__profitmax_curve(self, n)
      },
      optimise_psi_stem_ProfitMax = function() {
        Leaf__optimise_psi_stem_ProfitMax(self)
      },
      optimise_psi_stem_TF = function() {
        Leaf__optimise_psi_stem_TF(self)
      },
      medlyn_model_gs = function(assim_colimited_) {
        Leaf__medlyn_model_gs(self, assim_colimited_)
      },
      solve_medlyn_ci_numerical = function() {
        Leaf__solve_medlyn_ci_numerical(self)
      },
      solve_medlyn_ci_analytical = function() {
        Leaf__solve_medlyn_ci_analytical(self)
      },
      set_supply_multilayer = function() {
        Leaf__set_supply_multilayer(self)
      },
      set_supply_single = function(gravity_head) {
        Leaf__set_supply_single(self, gravity_head)
      },
      setup_transpiration = function(resolution) {
        Leaf__setup_transpiration(self, resolution)
      },
      setup_root_vulnerability = function(resolution) {
        Leaf__setup_root_vulnerability(self, resolution)
      }),
    active=list(
      vcmax_25 = function(value) {
        if (missing(value)) {
          Leaf__vcmax_25__get(self)
        } else {
          stop("Leaf$vcmax_25 is read-only")
        }
      },
      jmax_25 = function(value) {
        if (missing(value)) {
          Leaf__jmax_25__get(self)
        } else {
          stop("Leaf$jmax_25 is read-only")
        }
      },
      stem_c = function(value) {
        if (missing(value)) {
          Leaf__stem_c__get(self)
        } else {
          stop("Leaf$stem_c is read-only")
        }
      },
      stem_b = function(value) {
        if (missing(value)) {
          Leaf__stem_b__get(self)
        } else {
          stop("Leaf$stem_b is read-only")
        }
      },
      psi_crit = function(value) {
        if (missing(value)) {
          Leaf__psi_crit__get(self)
        } else {
          stop("Leaf$psi_crit is read-only")
        }
      },
      root_c = function(value) {
        if (missing(value)) {
          Leaf__root_c__get(self)
        } else {
          stop("Leaf$root_c is read-only")
        }
      },
      root_b = function(value) {
        if (missing(value)) {
          Leaf__root_b__get(self)
        } else {
          stop("Leaf$root_b is read-only")
        }
      },
      root_psi_crit = function(value) {
        if (missing(value)) {
          Leaf__root_psi_crit__get(self)
        } else {
          stop("Leaf$root_psi_crit is read-only")
        }
      },
      beta2 = function(value) {
        if (missing(value)) {
          Leaf__beta2__get(self)
        } else {
          stop("Leaf$beta2 is read-only")
        }
      },
      a = function(value) {
        if (missing(value)) {
          Leaf__a__get(self)
        } else {
          stop("Leaf$a is read-only")
        }
      },
      curv_fact_elec_trans = function(value) {
        if (missing(value)) {
          Leaf__curv_fact_elec_trans__get(self)
        } else {
          stop("Leaf$curv_fact_elec_trans is read-only")
        }
      },
      curv_fact_colim = function(value) {
        if (missing(value)) {
          Leaf__curv_fact_colim__get(self)
        } else {
          stop("Leaf$curv_fact_colim is read-only")
        }
      },
      cost_scale_TF24 = function(value) {
        if (missing(value)) {
          Leaf__cost_scale_TF24__get(self)
        } else {
          stop("Leaf$cost_scale_TF24 is read-only")
        }
      },
      ci_ = function(value) {
        if (missing(value)) {
          Leaf__ci___get(self)
        } else {
          Leaf__ci___set(self, value)
        }
      },
      stom_cond_CO2_ = function(value) {
        if (missing(value)) {
          Leaf__stom_cond_CO2___get(self)
        } else {
          Leaf__stom_cond_CO2___set(self, value)
        }
      },
      assim_colimited_ = function(value) {
        if (missing(value)) {
          Leaf__assim_colimited___get(self)
        } else {
          Leaf__assim_colimited___set(self, value)
        }
      },
      transpiration_ = function(value) {
        if (missing(value)) {
          Leaf__transpiration___get(self)
        } else {
          Leaf__transpiration___set(self, value)
        }
      },
      soil_consumption_ = function(value) {
        if (missing(value)) {
          Leaf__soil_consumption___get(self)
        } else {
          Leaf__soil_consumption___set(self, value)
        }
      },
      profit_ = function(value) {
        if (missing(value)) {
          Leaf__profit___get(self)
        } else {
          Leaf__profit___set(self, value)
        }
      },
      psi_stem = function(value) {
        if (missing(value)) {
          Leaf__psi_stem__get(self)
        } else {
          Leaf__psi_stem__set(self, value)
        }
      },
      lambda_ = function(value) {
        if (missing(value)) {
          Leaf__lambda___get(self)
        } else {
          Leaf__lambda___set(self, value)
        }
      },
      carbon_gain_ = function(value) {
        if (missing(value)) {
          Leaf__carbon_gain___get(self)
        } else {
          Leaf__carbon_gain___set(self, value)
        }
      },
      hydraulic_cost_norm_ = function(value) {
        if (missing(value)) {
          Leaf__hydraulic_cost_norm___get(self)
        } else {
          Leaf__hydraulic_cost_norm___set(self, value)
        }
      },
      thermal_cost_ = function(value) {
        if (missing(value)) {
          Leaf__thermal_cost___get(self)
        } else {
          Leaf__thermal_cost___set(self, value)
        }
      },
      hydraulic_cost_ = function(value) {
        if (missing(value)) {
          Leaf__hydraulic_cost___get(self)
        } else {
          Leaf__hydraulic_cost___set(self, value)
        }
      },
      opt_psi_stem_ = function(value) {
        if (missing(value)) {
          Leaf__opt_psi_stem___get(self)
        } else {
          Leaf__opt_psi_stem___set(self, value)
        }
      },
      opt_root_psi_ = function(value) {
        if (missing(value)) {
          Leaf__opt_root_psi___get(self)
        } else {
          Leaf__opt_root_psi___set(self, value)
        }
      },
      opt_ci_ = function(value) {
        if (missing(value)) {
          Leaf__opt_ci___get(self)
        } else {
          Leaf__opt_ci___set(self, value)
        }
      },
      E_up_ = function(value) {
        if (missing(value)) {
          Leaf__E_up___get(self)
        } else {
          Leaf__E_up___set(self, value)
        }
      },
      assim_max_ = function(value) {
        if (missing(value)) {
          Leaf__assim_max___get(self)
        } else {
          Leaf__assim_max___set(self, value)
        }
      },
      count = function(value) {
        if (missing(value)) {
          Leaf__count__get(self)
        } else {
          Leaf__count__set(self, value)
        }
      },
      Tleaf_ = function(value) {
        if (missing(value)) {
          Leaf__Tleaf___get(self)
        } else {
          Leaf__Tleaf___set(self, value)
        }
      },
      electron_transport_ = function(value) {
        if (missing(value)) {
          Leaf__electron_transport___get(self)
        } else {
          Leaf__electron_transport___set(self, value)
        }
      },
      gamma_ = function(value) {
        if (missing(value)) {
          Leaf__gamma___get(self)
        } else {
          Leaf__gamma___set(self, value)
        }
      },
      ko_ = function(value) {
        if (missing(value)) {
          Leaf__ko___get(self)
        } else {
          Leaf__ko___set(self, value)
        }
      },
      kc_ = function(value) {
        if (missing(value)) {
          Leaf__kc___get(self)
        } else {
          Leaf__kc___set(self, value)
        }
      },
      km_ = function(value) {
        if (missing(value)) {
          Leaf__km___get(self)
        } else {
          Leaf__km___set(self, value)
        }
      },
      R_d_ = function(value) {
        if (missing(value)) {
          Leaf__R_d___get(self)
        } else {
          Leaf__R_d___set(self, value)
        }
      },
      vcmax_ = function(value) {
        if (missing(value)) {
          Leaf__vcmax___get(self)
        } else {
          Leaf__vcmax___set(self, value)
        }
      },
      jmax_ = function(value) {
        if (missing(value)) {
          Leaf__jmax___get(self)
        } else {
          Leaf__jmax___set(self, value)
        }
      },
      vcmax_ha_ = function(value) {
        if (missing(value)) {
          Leaf__vcmax_ha___get(self)
        } else {
          Leaf__vcmax_ha___set(self, value)
        }
      },
      vcmax_H_d_ = function(value) {
        if (missing(value)) {
          Leaf__vcmax_H_d___get(self)
        } else {
          Leaf__vcmax_H_d___set(self, value)
        }
      },
      vcmax_d_S_ = function(value) {
        if (missing(value)) {
          Leaf__vcmax_d_S___get(self)
        } else {
          Leaf__vcmax_d_S___set(self, value)
        }
      },
      jmax_ha_ = function(value) {
        if (missing(value)) {
          Leaf__jmax_ha___get(self)
        } else {
          Leaf__jmax_ha___set(self, value)
        }
      },
      jmax_H_d_ = function(value) {
        if (missing(value)) {
          Leaf__jmax_H_d___get(self)
        } else {
          Leaf__jmax_H_d___set(self, value)
        }
      },
      jmax_d_S_ = function(value) {
        if (missing(value)) {
          Leaf__jmax_d_S___get(self)
        } else {
          Leaf__jmax_d_S___set(self, value)
        }
      },
      gamma_25_ = function(value) {
        if (missing(value)) {
          Leaf__gamma_25___get(self)
        } else {
          Leaf__gamma_25___set(self, value)
        }
      },
      gamma_ha_ = function(value) {
        if (missing(value)) {
          Leaf__gamma_ha___get(self)
        } else {
          Leaf__gamma_ha___set(self, value)
        }
      },
      kc_25_ = function(value) {
        if (missing(value)) {
          Leaf__kc_25___get(self)
        } else {
          Leaf__kc_25___set(self, value)
        }
      },
      kc_ha_ = function(value) {
        if (missing(value)) {
          Leaf__kc_ha___get(self)
        } else {
          Leaf__kc_ha___set(self, value)
        }
      },
      ko_25_ = function(value) {
        if (missing(value)) {
          Leaf__ko_25___get(self)
        } else {
          Leaf__ko_25___set(self, value)
        }
      },
      ko_ha_ = function(value) {
        if (missing(value)) {
          Leaf__ko_ha___get(self)
        } else {
          Leaf__ko_ha___set(self, value)
        }
      },
      R_d_25 = function(value) {
        if (missing(value)) {
          Leaf__R_d_25__get(self)
        } else {
          Leaf__R_d_25__set(self, value)
        }
      },
      rd_q10_intercept_ = function(value) {
        if (missing(value)) {
          Leaf__rd_q10_intercept___get(self)
        } else {
          Leaf__rd_q10_intercept___set(self, value)
        }
      },
      rd_q10_slope_ = function(value) {
        if (missing(value)) {
          Leaf__rd_q10_slope___get(self)
        } else {
          Leaf__rd_q10_slope___set(self, value)
        }
      },
      PPFD_ = function(value) {
        if (missing(value)) {
          Leaf__PPFD___get(self)
        } else {
          Leaf__PPFD___set(self, value)
        }
      },
      atm_vpd_ = function(value) {
        if (missing(value)) {
          Leaf__atm_vpd___get(self)
        } else {
          Leaf__atm_vpd___set(self, value)
        }
      },
      ca_ = function(value) {
        if (missing(value)) {
          Leaf__ca___get(self)
        } else {
          Leaf__ca___set(self, value)
        }
      },
      leaf_temp_ = function(value) {
        if (missing(value)) {
          Leaf__leaf_temp___get(self)
        } else {
          Leaf__leaf_temp___set(self, value)
        }
      },
      atm_o2_kpa_ = function(value) {
        if (missing(value)) {
          Leaf__atm_o2_kpa___get(self)
        } else {
          Leaf__atm_o2_kpa___set(self, value)
        }
      },
      atm_kpa_ = function(value) {
        if (missing(value)) {
          Leaf__atm_kpa___get(self)
        } else {
          Leaf__atm_kpa___set(self, value)
        }
      },
      leaf_specific_conductance_max_ = function(value) {
        if (missing(value)) {
          Leaf__leaf_specific_conductance_max___get(self)
        } else {
          Leaf__leaf_specific_conductance_max___set(self, value)
        }
      },
      soil_depth_ = function(value) {
        if (missing(value)) {
          Leaf__soil_depth___get(self)
        } else {
          Leaf__soil_depth___set(self, value)
        }
      },
      z_soil_mid_ = function(value) {
        if (missing(value)) {
          Leaf__z_soil_mid___get(self)
        } else {
          Leaf__z_soil_mid___set(self, value)
        }
      },
      dz_ = function(value) {
        if (missing(value)) {
          Leaf__dz___get(self)
        } else {
          Leaf__dz___set(self, value)
        }
      },
      soil_number_of_depths_ = function(value) {
        if (missing(value)) {
          Leaf__soil_number_of_depths___get(self)
        } else {
          Leaf__soil_number_of_depths___set(self, value)
        }
      },
      max_soil_layer = function(value) {
        if (missing(value)) {
          Leaf__max_soil_layer__get(self)
        } else {
          Leaf__max_soil_layer__set(self, value)
        }
      },
      psi_soil_ = function(value) {
        if (missing(value)) {
          Leaf__psi_soil___get(self)
        } else {
          Leaf__psi_soil___set(self, value)
        }
      },
      c_r_V_ = function(value) {
        if (missing(value)) {
          Leaf__c_r_V___get(self)
        } else {
          Leaf__c_r_V___set(self, value)
        }
      },
      c_r_H_ = function(value) {
        if (missing(value)) {
          Leaf__c_r_H___get(self)
        } else {
          Leaf__c_r_H___set(self, value)
        }
      },
      r_R_H_min = function(value) {
        if (missing(value)) {
          Leaf__r_R_H_min__get(self)
        } else {
          Leaf__r_R_H_min__set(self, value)
        }
      },
      r_R_V = function(value) {
        if (missing(value)) {
          Leaf__r_R_V__get(self)
        } else {
          Leaf__r_R_V__set(self, value)
        }
      },
      r_R_V_sum = function(value) {
        if (missing(value)) {
          Leaf__r_R_V_sum__get(self)
        } else {
          Leaf__r_R_V_sum__set(self, value)
        }
      },
      f_r = function(value) {
        if (missing(value)) {
          Leaf__f_r__get(self)
        } else {
          Leaf__f_r__set(self, value)
        }
      },
      use_energy_balance_ = function(value) {
        if (missing(value)) {
          Leaf__use_energy_balance___get(self)
        } else {
          Leaf__use_energy_balance___set(self, value)
        }
      },
      vpd_leaf_ = function(value) {
        if (missing(value)) {
          Leaf__vpd_leaf___get(self)
        } else {
          Leaf__vpd_leaf___set(self, value)
        }
      },
      use_thermal_cost_ = function(value) {
        if (missing(value)) {
          Leaf__use_thermal_cost___get(self)
        } else {
          Leaf__use_thermal_cost___set(self, value)
        }
      },
      T50_ = function(value) {
        if (missing(value)) {
          Leaf__T50___get(self)
        } else {
          Leaf__T50___set(self, value)
        }
      },
      Tcrit_ = function(value) {
        if (missing(value)) {
          Leaf__Tcrit___get(self)
        } else {
          Leaf__Tcrit___set(self, value)
        }
      },
      profitmax_scan_n_ = function(value) {
        if (missing(value)) {
          Leaf__profitmax_scan_n___get(self)
        } else {
          Leaf__profitmax_scan_n___set(self, value)
        }
      },
      boundary_scan_n_ = function(value) {
        if (missing(value)) {
          Leaf__boundary_scan_n___get(self)
        } else {
          Leaf__boundary_scan_n___set(self, value)
        }
      },
      d_ = function(value) {
        if (missing(value)) {
          Leaf__d___get(self)
        } else {
          Leaf__d___set(self, value)
        }
      },
      wind_speed_ = function(value) {
        if (missing(value)) {
          Leaf__wind_speed___get(self)
        } else {
          Leaf__wind_speed___set(self, value)
        }
      },
      Tair_ = function(value) {
        if (missing(value)) {
          Leaf__Tair___get(self)
        } else {
          Leaf__Tair___set(self, value)
        }
      },
      Rn_ = function(value) {
        if (missing(value)) {
          Leaf__Rn___get(self)
        } else {
          Leaf__Rn___set(self, value)
        }
      },
      ra_ = function(value) {
        if (missing(value)) {
          Leaf__ra___get(self)
        } else {
          Leaf__ra___set(self, value)
        }
      },
      medlyn_model_gs_ = function(value) {
        if (missing(value)) {
          Leaf__medlyn_model_gs___get(self)
        } else {
          Leaf__medlyn_model_gs___set(self, value)
        }
      },
      g0 = function(value) {
        if (missing(value)) {
          Leaf__g0__get(self)
        } else {
          Leaf__g0__set(self, value)
        }
      },
      g1 = function(value) {
        if (missing(value)) {
          Leaf__g1__get(self)
        } else {
          Leaf__g1__set(self, value)
        }
      },
      theta_w_ = function(value) {
        if (missing(value)) {
          Leaf__theta_w___get(self)
        } else {
          Leaf__theta_w___set(self, value)
        }
      },
      theta_fc_ = function(value) {
        if (missing(value)) {
          Leaf__theta_fc___get(self)
        } else {
          Leaf__theta_fc___set(self, value)
        }
      },
      theta_ = function(value) {
        if (missing(value)) {
          Leaf__theta___get(self)
        } else {
          Leaf__theta___set(self, value)
        }
      },
      supply_kind = function(value) {
        if (missing(value)) {
          Leaf__supply_kind__get(self)
        } else {
          stop("Leaf$supply_kind is read-only")
        }
      },
      single_resistance_ = function(value) {
        if (missing(value)) {
          Leaf__single_resistance___get(self)
        } else {
          stop("Leaf$single_resistance_ is read-only")
        }
      },
      single_gravity_head_ = function(value) {
        if (missing(value)) {
          Leaf__single_gravity_head___get(self)
        } else {
          stop("Leaf$single_gravity_head_ is read-only")
        }
      },
      single_psi_soil_ = function(value) {
        if (missing(value)) {
          Leaf__single_psi_soil___get(self)
        } else {
          stop("Leaf$single_psi_soil_ is read-only")
        }
      },
      lambda = function(value) {
        if (missing(value)) {
          Leaf__lambda__get(self)
        } else {
          stop("Leaf$lambda is read-only")
        }
      },
      lambda_molar = function(value) {
        if (missing(value)) {
          Leaf__lambda_molar__get(self)
        } else {
          stop("Leaf$lambda_molar is read-only")
        }
      },
      lambda_multilayer = function(value) {
        if (missing(value)) {
          Leaf__lambda_multilayer__get(self)
        } else {
          stop("Leaf$lambda_multilayer is read-only")
        }
      },
      lambda_emergent = function(value) {
        if (missing(value)) {
          Leaf__lambda_emergent__get(self)
        } else {
          stop("Leaf$lambda_emergent is read-only")
        }
      },
      profitmax_A_max = function(value) {
        if (missing(value)) {
          Leaf__profitmax_A_max__get(self)
        } else {
          stop("Leaf$profitmax_A_max is read-only")
        }
      },
      profitmax_k_span = function(value) {
        if (missing(value)) {
          Leaf__profitmax_k_span__get(self)
        } else {
          stop("Leaf$profitmax_k_span is read-only")
        }
      },
      g1_eff = function(value) {
        if (missing(value)) {
          Leaf__g1_eff__get(self)
        } else {
          stop("Leaf$g1_eff is read-only")
        }
      },
      gs_H2O = function(value) {
        if (missing(value)) {
          Leaf__gs_H2O__get(self)
        } else {
          stop("Leaf$gs_H2O is read-only")
        }
      },
      H2O_CO2_stom_diff_ratio_ = function(value) {
        if (missing(value)) {
          Leaf__H2O_CO2_stom_diff_ratio___get(self)
        } else {
          Leaf__H2O_CO2_stom_diff_ratio___set(self, value)
        }
      }))


